### PR TITLE
dhcp_lease_counter for master

### PR DESCRIPTION
**Pull request by heper**
lease_counter_master
https://redmine.pfsense.org/issues/5186

related to: https://github.com/pfsense/pfsense/pull/1930
only tested on 2.2.5-dev with copied 'www' directory

### CODE REVIEW

**Comment by heper** [comment]
@rbgarga here's the 'same' commit as yesterday, but then for master

**Comment by rbgarga** [comment]
Thank you! @sbeaver-netgate can you check this patch?

**Comment by sbeaver-netgate** [comment]
The patch looks very nice. I see no issues with the code or the style. Thank you!

I do note that whomever converted the page to Bootstrap forgot to add the “table-responsive” class to the tables. I will take care of that globally after this contribution is merged.

Steve
--
Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com | www.netgate.com

**Comment by sbeaver-netgate** [comment]
I have made minor (mostly style) changes to the file to bring it into line with other recently "Bootstrapped" UI pages. Would you please check that the information displayed still conforms to your intentions?

**Comment by heper** [comment]
the displayed information seems to have remained the same.
thanks @rbgarga and @sbeaver-netgate 

collegue's have asked me to add the same data to rrd-graphs. running when you are barely able to walk, is generally not a good idea: but i'll give it a try when i find the time.

**Comment by sbeaver-netgate** [comment]
Thank you. I’m here to help when the time comes :)

**Pull request merged**
