### PR TITLE
add dhcpd rrd graphs

### PR DESCRIPTION
**Pull request by heper**
hi all.

so far, it appears i've gotten it working.
-dhcp_gather_stats is still bloated. could use some help cleaning it.

services_dhcp.php has a checkbox for each interface-tab:
rrd_services_dhcp
graphs itself:
rrd_dhcpd_graphs

### CODE REVIEW

**Comment by heper** [comment]
@sbeaver-netgate 
please check "workaround make_tabs() globals" in status_rrd_graph.php
is there a better way todo this ? in releng2_2 there wasn't a function for it, so perhaps you've added it?

**Comment by heper** [comment]
Feature #5387
https://redmine.pfsense.org/issues/5387

**Comment by heper** [comment]
changed graph style to lines:
rrd_dhcpd_graphsv2

**Comment by sbeaver-netgate** [comment]
Useful new capability. Thank you. 2.3 is not just a pretty face :)

**Pull request merged**
