### PR TITLE
Services / DNS Resolver / General Settings

### PR DESCRIPTION
**Pull request by NOYB**
Static should be static.
Elements that don't need to be dynamic should be static.
More robust than depending on client-side processing to set them.

### CODE REVIEW

**Comment by phil-davis** [comment]
There are about a dozen of these that were created this last week, because I was using a "template" of how the Advanced button code was done in services_dhcp
So I guess they all should be changed.
After this one gets committed (so we know that is the agreed way to go), I am happy to find the all and do the update.

**Comment by NOYB** [comment]
I for one definitely think they should be changed and welcome your offer.
In my opinion client-side processing on static items, adds unnecessary complexity and compatibility risk.

For instance in this particular case had this been static setting the JavaScript failure, fixed yesterday, would not have resulted in an unsuspected submit.  Instead it would have just failed to toggle its target.

**Comment by sbeaver-netgate** [comment]
I have no objection to this and agree that it is somewhat more robust. The change is not strictly necessary but since the matter was introduced (mostly) in a recent change, it is OK to fix it. There appear to be 16 instances of this altogether so not too bad a task (easy for me to say)

**Comment by phil-davis** [comment]
Commit this one whenever you like, and I will make a PR for the rest of them that will be waiting for you on Monday morning...

**Comment by sbeaver-netgate** [comment]
Thank you Phil.

**Pull request merged**
