### PR TITLE
Bug #6751 Pull Request

### PR DESCRIPTION
**Pull request by jxmx**
Code for the changes to the AWS Route53 dynamic DNS as filed in https://redmine.pfsense.org/issues/6751

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by jxmx** [comment]
Done

**Comment by jim-p** [comment]
Can you rebase your fork? This PR does not merge cleanly now.

**Comment by jxmx** [comment]
Should be good now.

**Pull request merged**
