### PR TITLE
Make UPNP presentation_url and model_number customizable

### PR DESCRIPTION
**Pull request by zevlag**
This patch it to make UPNP presentation_url and model_number customizable per the bounty request at: https://forum.pfsense.org/index.php?topic=106193.0

### CODE REVIEW

**Comment by sbeaver-netgate** [comment]
Closing for now since 2.3 is "bugfix only" at the moment. Please reopen for consideration after 2.3 is released.

**Comment by cbuechler** [comment]
Reopening to merge post-2.3, shouldn't be a need to re-submit.

**Comment by djzort** [comment]
can merge now?

**Comment by cbuechler** [comment]
Thanks @djzort, merged to master and 2_3, will be in next 2.3.2 snapshot. Sorry this took a bit to get merged.

**Pull request merged**
