### PR TITLE
ipsec: set retransmission parameters for IKEv2 auth and dpd.

### PR DESCRIPTION
**Pull request by laped83**
Added strongswan charon retranmission values (tries, timeout and base) to advanced ipsec settings.

Signed-off by: Lars Alex Pedersen <thacaleb@gmail.com>

### CODE REVIEW

**Comment by laped83** [comment]
Update pfsense doc:
https://doc.pfsense.org/index.php/Advanced_IPsec_Settings

with retransmission information at:
https://wiki.strongswan.org/projects/strongswan/wiki/Retransmission

**Comment by laped83** [comment]
Okay seems like this branch it kinda hard to get merged after master has changed to bootstrap :)

I am considering starting over and maybe changing the way to add change settings in strongswan.conf. Strongswan.conf has a lot of configuration values so what do you guys think about making something that looks like the "Advanced System Tunables" with "section, description, value"? A set of default values is presented but the user can also add additional settings. This way the user will have access to all settings in https://wiki.strongswan.org/projects/1/wiki/StrongswanConf.

**Comment by rbgarga** [comment]
What do you think about this change and about the ide from last comment @cbuechler ?

**Comment by cbuechler** [comment]
I've been contemplating this and other options, there are a bunch of other configurable knobs in strongswan that the vast majority don't need, but some small portion do. I agree with @laped83 's last comment re: adding a tunables list of sorts like the sysctl one now, that's the thing I was leaning towards for options like the ones covered here, plus that would cover all the other ones. If we kept adding to the current advanced tab it'd end up being unwieldy. That should also discourage people from mucking with things they shouldn't be.

**Pull request closed without merging**
