### PR TITLE
Improve dns error message for duplicated aliases

### PR DESCRIPTION
**Pull request by S33G**
- [x] Ready for review

### CODE REVIEW

**Comment by marcos-ng** [comment]
Change it to `Alias already exists for %s`. Should be good to merge after.

**Comment by S33G** [comment]
> Change it to `Alias already exists for %s`. Should be good to merge after.

done

**Comment by marcos-ng** [comment]
Thank you for the contribution. I've added the adjusted error as a single commit with a slightly different message: c48865bc737d98268d0fc679b2751e7566fef424

**Comment by calebjonasson** [comment]
@jim-p and @rbgarga Do you have any guidance around someone sniping PRs to pad their git/contribution numbers?

@S33G Maybe write into [coreteam@pfsense.org](mailto:coreteam@pfsense.org) to see if they have any suggestions.

This goes against the spirit of open source collaboration and I suspect this behaviour is something that Pfsense would want to address.

**Comment by marcos-ng** [comment]
I'm sorry you feel that way, no harm is intended.

The reasons for committing it separately are:
- A new release is almost here and I wanted to make sure it was included in time.
- Normally public PRs require a redmine link and proper commit history and message.
- I preferred that the string change followed existing error messages on the page; your commit implied you did not agree with that.
- The change is a very minor string adjustment with no functional difference.

I'll give further consideration to this kind of situation in the future.

**Comment by S33G** [comment]
1. Requiring me to register for an account to raise a bug for a simple message change is ridiculous
2. Not sure what this refers to as I adjusted the message to exactly what you suggested.

- What is "proper commit history"?
- Your change bypassed PR completely?

3. Though a minor change, you should still respect the open source process

**Comment by S33G** [comment]
FYI (From your own contribution guidelines):

> Ensure the bug or feature has an entry on the [pfSense Redmine](https://redmine.pfsense.org/)
> [Create a new entry](https://docs.netgate.com/pfsense/en/latest/development/bug-reports.html) if one does not exist.
> The only exceptions to this are for very minor typo/wording fixes.

Found here:
https://docs.netgate.com/pfsense/en/latest/development/pull-request.html#submitting-a-pull-request-via-github

**Pull request closed without merging**
