### PR TITLE
webgui, option to disable dragging of rules

### PR DESCRIPTION
**Pull request by PiBa-NL**

### CODE REVIEW

**Comment by sbeaver-netgate** [comment]
Why is this needed?

**Comment by PiBa-NL** [comment]
Disables dragging rows to allow selecting and copying row contents and avoid accidental changes.

**Comment by sbeaver-netgate** [comment]
Please resolve the conflicts.

**Comment by PiBa-NL** [comment]
@sbeaver-netgate , conflict resolved

**Pull request merged**
