### PR TITLE
Interfaces - Assign - Wireless - PHP Crash

### PR DESCRIPTION
**Pull request by NOYB**
Fix unexpected EOF

### CODE REVIEW

**Comment by phil-davis** [comment]
Hmm - I broke that :(

**Comment by NOYB** [comment]
No worries.  I fixed.

**Comment by sbeaver-netgate** [comment]
Seems like a good time to thank you both again for all you do here. It help so many people.

Steve

**Comment by NOYB** [comment]
Thank you Steve.  Appreciate the complement.

**Comment by phil-davis** [comment]
Thanks also. We all complement each other, and thanks for the compliment.
http://www.quickanddirtytips.com/education/grammar/compliment-versus-complement?page=all
:)

**Pull request merged**
