### PR TITLE
guiconfig.inc - wrap inline JS/CSS in CDATA

### PR DESCRIPTION
**Pull request by doktornotor**
There functions screw up any kind of (X)HTML validation otherwise.

### CODE REVIEW

**Comment by ExolonDX** [comment]
You will want to remove the "CDATA" sections in:

    /usr/local/www/themes/{theme_name}/loader.js
    /usr/local/www/themes/{theme_name}/bottom-loader.js

Other wise you'll get duplicate "CDATA" sections.

**Comment by ExolonDX** [comment]
Sorry, and also check:

    /usr/local/www/javascript/.....

**Comment by doktornotor** [comment]
Well, this was an idea to make the functions actually usable. I certainly do not have time to wade through heaps of javascript scattered across the repo to check which single pieces of those by some accident ship the CDATA already, sorry.

Forget this. Might as well nuke the functions altogether, they are unusable as it is.

**Comment by cbuechler** [comment]
this kind of change should probably be put on hold for the moment, or done against the bootstrap branch since that is likely to be what 2.3 becomes (for the moment, bootstrap branch here: https://github.com/sbeaver-netgate/pfsense)

**Comment by doktornotor** [comment]
Yeah indeed, digging into JS that's gonna get to /dev/null for most part is just waste of time. ;)

**Pull request closed without merging**
