### PR TITLE
Add IPv6 support for Gandi LiveDNS dynamic DNS handler

### PR DESCRIPTION
**Pull request by bitscher**
* Add support for AAAA records with Gandi LiveDNS.
* Simplify the use of the LiveDNS API by using another API call that
handles both creating and updating for a given name and record type
instead of the former two step operation that was fetching the whole
content of the zone file and looked for the relevant record to update.
https://api.gandi.net/docs/livedns/#v5-livedns-domains-fqdn-records-rrset_name-rrset_type
* Remove duplicated code by merging relevant switch statements.
* Fix erroneous input validation for hosts '@.' and '*.' that are
not supported by Gandi LiveDNS and should not be saved in config.

- [x] Redmine Issue: https://redmine.pfsense.org/issues/11420
- [x] Ready for review

### CODE REVIEW

**Review by jim-p — APPROVED** [review]

**Comment by bitscher** [comment]
Is it realistic to have this change merged into the 2.5 branch as well?

**Comment by jim-p** [comment]
No, it's too late for it to get into 2.5.0.

**Comment by bitscher** [comment]
Understandable, I'll just keep patching it manually after updates.

**Comment by bitscher** [comment]
I'm not familiar with the release process, is it something that could be submited for 2.5.1 once 2.5.0 is out the door?
What will be the working branch for checking in changes for the upcoming 2.5.1?

**Comment by jim-p** [comment]
It has to go into master first, which is now 2.6.0. Once it is in there and working, it could be considered for picking back to 2.5.1 or whatever the next release may be.

**Pull request merged**
