### PR TITLE
Backup IPsec: MSS clamping. Wrong group location used.

### PR DESCRIPTION
**Pull request by laped83**
MSS value of IPsec isn't backed up when selecting IPsec, because its in the wrong config group.

Now uses "IPsec" instead of "System" group.

Signed-off by: Lars Alex Pedersen <thacaleb@gmail.com>

### CODE REVIEW

**Comment by laped83** [comment]
To solve the following issue with backup of IPsec configuration values.

https://redmine.pfsense.org/issues/4864

**Comment by cbuechler** [comment]
This will break MSS clamping on every existing install. If we're going to move it, it needs config upgrade code as well.

**Comment by laped83** [comment]
Added config upgrade code.

**Comment by doktornotor** [comment]
Pardon me, but... This is used for ```<vpn_networks>``` table:

```
        if (isset($config['system']['maxmss_enable'])) {
                $maxmss = 1400;
                if (!empty($config['system']['maxmss']))
                        $maxmss = $config['system']['maxmss'];

                $scrubrules .= "scrub from any to <vpn_networks> max-mss {$maxmss}\n";
                $scrubrules .= "scrub from <vpn_networks> to any max-mss {$maxmss}\n";
        }
```

which boils down to filter_get_vpns_list() in filter.inc. There are things such as OpenVPN there, plus also PPPoE. How on earth is this ipsec-specific setting? This is actually breaking things, this is system-wide setting and should stay where it is. If there's supposed to be something IPSec-specific as well, then you'd better start fixing different parts of code.

**Comment by rbgarga** [comment]
Max MSS parameter is used by IPsec, OpenVPN and PPPoE server, that is the reason it's a global setting in System -> Advanced.

If you want to have specific values for all kinds of VPNs a different patch should be done considering all the cases

**Pull request closed without merging**
