### PR TITLE
Remove dashboard update period references

### PR DESCRIPTION
**Pull request by doktornotor**
No-op code since https://github.com/pfsense/pfsense/commit/6c1f2a1ce66e201ddfdaf926275c021161b65ad2

### CODE REVIEW

**Comment by rbgarga** [comment]
@doktornotor please rebase your fork

**Comment by doktornotor** [comment]
@rbgarga Done (hopefully...)

**Comment by doktornotor** [comment]
Well yes, that's another source of conflicts unfortunately...

**Comment by doktornotor** [comment]
Errr. this produce another round of conflicts and I'm really not going to keep redoing this over and over again. Resolved for now.

**Comment by doktornotor** [comment]
In case you are wondering why this PR is closed, see https://github.com/doktornotor/pfsense-closedsource

I'm not willing to contribute to closed-source projects that are falsely advertising themselves as open-source any more.

**Pull request closed without merging**
