### PR TITLE
Gateway down policy rule fix. Issue #10716

### PR DESCRIPTION
**Pull request by vktg**
- [X] Redmine Issue: https://redmine.pfsense.org/issues/10716
- [X] Ready for review

Fixes PBR rules creation when:
- Gateway is down
- Gateway in gateways group is down or disabled (`force_down`)

### CODE REVIEW

**Comment by stephenw10** [comment]
This correctly omits the rule entirely when 'Skip rules when gateway is down` is selected but it does not omit the gateway from the rule in the default setting.
Gateway looks like:
`GWGW2 = "  "`
But the rule still contains it:
`pass  in  quick  on $LAN  $GWGW2 inet proto tcp  from any to 9.9.9.9 tracker 1593470028 flags S/SA keep state  label "USER_RULE"`

**Comment by stephenw10** [comment]
But of course since the value of $GWGW2 is now '  ' that does omit it!

**Comment by vktg** [comment]
Gateways Group 'Trigger Level' also needs to be considered,
with the latest changes in this PR it only checks for 'Member Down' state

**Comment by vktg** [comment]
Updated
Gateways Group 'Trigger Level' and 'Disable Gateway Monitoring Action' check added

**Comment by stephenw10** [comment]
Tested this. Looks good. Gateway is marked down and removed from ruleset and/or rules removed as expected.

**Pull request merged**
