### PR TITLE
Adding Route 53 v6 

### PR DESCRIPTION
**Pull request by chewrocca**
Adding option to use Route 53 v6 for Dynamic DNS services.

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by chewrocca** [comment]
submitted signed CLA.

**Comment by sbeaver-netgate** [comment]
Please resolve conflict

**Comment by chewrocca** [comment]
fixed conflicts.

**Pull request merged**
