### PR TITLE
Add missing includes to config.console.inc

### PR DESCRIPTION
**Pull request by doktornotor**
Part of https://redmine.pfsense.org/issues/7385

### CODE REVIEW

**Comment by phil-davis** [comment]
What is breaking without these?

**Comment by doktornotor** [comment]
@phil-davis - I did not see anything breaking - it would definitely break though if you were to include this file on its own in your own code. I don't think it's a good practice to rely on some magic happening behind the scenes so that in the end you are lucky enough to end up with the required includes being loaded indirectly by some other files.

**Comment by phil-davis** [comment]
True - e.g. in Diag->Command Prompt when executing some PHP that needs it, it is nice if config.console.inc knows how to include everything that it needs itself.

**Comment by doktornotor** [comment]
I filed https://redmine.pfsense.org/issues/7385 about this as it seems it's broken pretty much everywhere. (Fixed a bunch of those in some pending PRs here, but it gets boring and annoying pretty fast.)

**Pull request merged**
