### PR TITLE
diag_logs_filter reduce duplicated icon code

### PR DESCRIPTION
**Pull request by phil-davis**
Almost all the code in old lines 457 and 462 was the same. Make the logic a bit clearer about exactly what is the difference and hopefully reduce future code maintenance issues.

### CODE REVIEW

**Comment by phil-davis** [comment]
Somehow there is a commit from 3 hours ago that was not there 1 hour ago when I made this change - time travel?
I will resubmit...

**Comment by sbeaver-netgate** [comment]
Could be me. I made a commit, then had a network issue that prevented me from pushing until just now.

I think I have merged, updated and fixed such that all three files are now correct :)

Thanks,

Steve
--
Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com | www.netgate.com

**Comment by phil-davis** [comment]
New PR https://github.com/pfsense/pfsense/pull/2022

**Comment by sbeaver-netgate** [comment]
Merged. Thanks.


Steve
--
Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com | www.netgate.com

**Pull request closed without merging**
