### PR TITLE
Handle widgets having no items selected for display

### PR DESCRIPTION
**Pull request by phil-davis**
1) The existing code is a bit "surprising". If the user unchecks all items and presses save, then it behaves as if all items are checked (i.e. everything displays).

2) If there were some items checked for display (e.g. some WoL entries or...) and those items have since been deleted from the config, then in practice there will be no entries that get displayed.

For both cases it seems useful/reasonable that the widget displays the fact that there is nothing selected for display. Without doing this, users are likely to wonder why the widget is empty.

### CODE REVIEW

**Comment by phil-davis** [comment]
Note: This is some code that formed the first part of other PRs that add extra functionality to selection and layout of dashboard widgets. But those PRs have languished for some weeks with no response.

@sbeaver-netgate @jim-p @rbgarga  I don't know what is going on with the stop to feedback on community contributions over the last weeks, but it would be nice to at least get feedback on PRs (so we can progress any review comments) and to know when (or if) community contributions will begin to be accepted again.

**Comment by sbeaver-netgate** [comment]
An upgrade to our git servers necessitated we pause the PR merges for a little while. We expect to address the backlog in the next few days. Sorry for the inconvenience.

**Comment by phil-davis** [comment]
This will easily back-port to 2.3.*

**Comment by phil-davis** [comment]
@sbeaver-netgate not sure why it told me there was a conflict, I ended up with no-change to the code after resolving. Anyway, it is happy now.

**Comment by phil-davis** [comment]
@sbeaver-netgate This is ready. The sooner these things can get merged, the easier it is to work on top.

**Pull request merged**
