### PR TITLE
Add support for DNSimple in dynamic dns service

### PR DESCRIPTION
**Pull request by surrural**

### CODE REVIEW

**Comment by rbgarga** [comment]
In order to get patches applied you must sign Individual or Corporate CLA as described at https://www.pfsense.org/about-pfsense/#legal

**Comment by surrural** [comment]
Done! As of 2/16 :)

**Comment by rbgarga** [comment]
This Pull Request cannot be automatically merged, can you please rebase your fork?

**Comment by rbgarga** [comment]
I couldn't find your CLA, what is the username?

**Comment by surrural** [comment]
Grr. Typo in my pfsense portal username. It's "surrual".

I'll do a rebase...

**Comment by rbgarga** [comment]
Now I can see you :)
Will wait rebase and do the tests

**Comment by surrural** [comment]
Ok, first time with using github, but I think I've got it rebased successfully.

**Comment by stevenhaddox** [comment]
Is this still present in pfsense 2.2.6? I'm looking all over in the Dynamic DNS service and I can't find "DNSimple" anywhere. It looks like it's still in the relevant code on master, but I haven't familiarized mysel with the pfsense code base at all yet (sorry).

Am I just looking in the wrong area in pfsense possibly? Thanks for any help!

**Comment by ariestar** [comment]
Same here, looking for it in 2.2.6 without any luck.. Also tried the System Patches package to pull these changes in, but most probably I don't know exactly how it works.. any advice is greatly appreciated, thanks

**Comment by surrural** [comment]
Same. I haven't seen this show up in any of the releases since they were merged. Not sure what the story is.

**Comment by stevenhaddox** [comment]
@surrural: Are we able to apply your commit as a .patch to pfsense safely somehow?

**Comment by jim-p** [comment]
This was merged into master (pfSense 2.3) and is not available on pfSense 2.2.x. If you'd like to try it, test out the pfSense 2.3 beta at https://snapshots.pfsense.org -- trying to graft it into 2.2.x is unlikely to succeed without significant work.

**Comment by surrural** [comment]
Ah, thanks @jim-p. That makes sense.

**Comment by stevenhaddox** [comment]
@jim-p thanks. I assumed (naively) that a pull request merged in almost a year ago would have been in the latest release. Thanks for the solution and sorry for the misreport on my part.

**Pull request merged**
