### PR TITLE
Firewall / Rules - Page Efficiency Upgrade

### PR DESCRIPTION
**Pull request by NOYB**
Add is_array test and change !empty test to is_array test.

### CODE REVIEW

**Comment by sbeaver-netgate** [comment]
I already pushed a change that is almost the same as this and the DEV team have tested it. Would you take a look at that please and let me know if this PR adds anything?

**Comment by cbuechler** [comment]
@sbeaver-netgate wasn't the change you're referencing was just in upgrade_config.inc? 

This looks legit. The checking whether $config['filter']['rule'] is an array should always be unnecessary since I don't think short of manually editing the config it's possible for that to not be an array, but it's a good check to have regardless. The foreach on $separators likely hasn't triggered an error because it's never been passed anything other than an array, but is_array is better than !empty there and may prevent PHP from throwing errors in the future.

**Comment by sbeaver-netgate** [comment]
Yes. You are right. The code is so similar I didn't notice this was another instance. This is fine.

**Comment by NOYB** [comment]
Yeah I think you are referring to the upgrade script function.
That triggered me to take a look at these two functions in filter.inc.

**Pull request merged**
