### PR TITLE
add Strato dyndns provider

### PR DESCRIPTION
**Pull request by dneuhaeuser**
this adds the german provider "strato.de" to the list of dyndns services

- [x] Redmine Issue: https://redmine.pfsense.org/issues/11978
- [x] Ready for review

### CODE REVIEW

**Comment by arfett** [comment]
"Last Tested: 29 Mai 2021" should be "Last Tested: 29 May 2021"

**Comment by dneuhaeuser** [comment]
> "Last Tested: 29 Mai 2021" should be "Last Tested: 29 May 2021"

corrected! thank you!

**Review by jim-p — APPROVED** [review]
Looks OK but will need rebased/reworked significantly after #4523 is merged.

**Comment by rbgarga** [comment]
@dneuhaeuser please rebase your fork and make sure the change respect recently change that sorted all entries alphabetically

**Comment by dneuhaeuser** [comment]
conflicts are resolved

**Comment by rbgarga** [comment]
Manually merged it after squash all commits and cleanup some extra space added.  Thanks

**Pull request closed without merging**
