### PR TITLE
pkg_edit.php fix interfaces_selection option while using row_helpers

### PR DESCRIPTION
**Pull request by marcelloc**
current code does not show interface_selection properly while using row_helpers

### CODE REVIEW

**Comment by doktornotor** [comment]
Resubmitted as #1920

**Comment by doktornotor** [comment]
@marcelloc Since my resubmit was not acceptable due to authorship, you can either take that code from my PR referenced above and resubmit this yourself (it will probably only keep working for a couple of days at best before there's another bunch of conflicts), or live with the bug in pfSense code.

Nothing more I could do here, sorry for the waste of your time.

Have a nice day.

**Comment by marcelloc** [comment]
@doktornotor, You're not wasting my time in any way. Thank's for all work you're doing to fix a lot of bugs on pfSense packages and core. In the past, contributions was something like collaboration with main devs but IMHO these days, free code and time we waste to get pfSense better does not get any attention and good code get invalidated by minor issues that can be fixed by reviewer it it's receives it as collaboration instead of junk code.

**Comment by rbgarga** [comment]
@sbeaver-netgate can you please check this issue when you are converting pkg_edit.php?

**Pull request closed without merging**
