### PR TITLE
Trigger for external script when gateway status changes

### PR DESCRIPTION
**Pull request by deajan**
Adds a way for users to execute trivial code when a gateway is added or removed from a LB group.
Needed to make squid use failover & loadbalancing toghether, see https://forum.pfsense.org/index.php?topic=109000
I've asked if such a trigger exists before here: https://forum.pfsense.org/index.php?topic=112619.0

### CODE REVIEW

**Comment by rbgarga** [comment]
If users manually insert code inside gateway_status.sh, what in my opinion is a bad idea, changes will be lost during the first upgrade it runs, since file will be overwritten.

**Comment by deajan** [comment]
Renaming this file to a template solves this issue I think.

**Comment by rbgarga** [comment]
It would still have issues since custom scripts will not be part of backup/restore.

Other packages also could benefit of such mechanism that let it know when a gateway goes up/down, so we need a more generic implementation. I'll take a look at the code and try to think about a different approach

**Comment by deajan** [comment]
Any news about this ?

**Comment by loos-br** [comment]
It need to be redone, there is a plugin method used by packages that need to get CARP state events.

That is the way to go.

**Comment by deajan** [comment]
@loos-br Hmm, I'm not used to pfSense source.
Care to tell me where to dig so I can redo the PR ? Thanks

**Comment by loos-br** [comment]
Committed in:
https://github.com/pfsense/pfsense/commit/ca8ab3c958ace8fb42eb2f00cea7db74ae0bf707

Here is a plugin implementation example:
https://github.com/pfsense/FreeBSD-ports/blob/devel/net/pfSense-pkg-OpenBGPD/files/usr/local/pkg/openbgpd.inc#L409
https://github.com/pfsense/FreeBSD-ports/blob/devel/net/pfSense-pkg-OpenBGPD/files/usr/local/pkg/openbgpd.xml#L65

**Pull request closed without merging**
