### PR TITLE
User Configurable DUID

### PR DESCRIPTION
**Pull request by marjohn56**
A DUID may be entered in WAN DHCP6 section. The entered DUID is checked
for validity and then on call of interface_dhcpv6_configure a duid file
is written to /var/db

I hope there are no typos' or other in this PR. Once this is accepted I will issue the no-release PR

### CODE REVIEW

**Comment by rbgarga** [comment]
This PR depends of https://github.com/pfsense/FreeBSD-ports/pull/231

**Comment by marjohn56** [comment]
No it doesn't thats for no-release... this is just the duid bit. :)

**Comment by rbgarga** [comment]
oh, my bad, I'll remove the comment :)

**Comment by marjohn56** [comment]
The only thing I would like to change us the if ($fd = fopen("/var/db/dhcp6c_duid", "wb")) {

I could  not get the vardb path to work for some reason, kept writing to the root folder.

**Comment by rbgarga** [comment]
@marjohn56 you need to add a 'global $g;' at function begin

**Comment by marjohn56** [comment]
Ahah!! OK, Is it OK just to edit it here rather then re-submit?

**Comment by rbgarga** [comment]
sure

**Comment by marjohn56** [comment]
Done..

**Comment by marjohn56** [comment]
Copy paste error :)

**Comment by marjohn56** [comment]
Sheesh... then I missed the filename!

**Comment by marjohn56** [comment]
Is it possible to ignore the last three commits. i.e. merge remote etc. I tried to create a new branch in Desktop Github and made a complete horses arse of it. The only thing I can do now is wait for the DUID stuff to be accepted and then delete my repo and take it from there.

**Comment by rbgarga** [comment]
@marjohn56 you can remove these last 3 commits from your branch and push with -f to force it. Then this PR will be updated automagically

**Comment by rbgarga** [comment]
Superseded by #3294

**Pull request closed without merging**
