### PR TITLE
Add comprehensive high-level ip_compare() function

### PR DESCRIPTION
**Pull request by stilez**
A lot of end code needs to do IP/range/subnet comparisons, and detect features such as overlap, disjoint (non-overlap), containment (full inclusion), as well as the more usual < = > != type of comparison. These need to work over agnostic IPs as well as sometimes restricted to IPv4 or IPv6 by calling code. So util.inc contains a proliferation of comparison functions. 

Despite this, we still don't have several comparisons that are often needed (for example, an equivalent to check_subnets_overlap() for testing range overlap, or range v subnet overlap). These are often needed when validating DHCP, VPN and other IP data.

Rather than create new functions for each of these, this PR creates a comprehensive but straightforward generic ip comparison function ip_compare() that handles in one go, all comparisons of ip/subnet/range/IPv4/IPv6 that are likely to be needed, and which is fast and efficient.

Features:
-     ip, range or subnet comparison
-     handles input in string and factored form, so if a subnet is stored as ip/netmask already, or a range stored as start/end, it doesn't need to be converted to string only to convert back
  -          subnet       '::fe80/64' evaluated same as array('subnet', '::fe80', 64)
  -         range         '192.168.1.10-192.168.1.19' evaluated same as array('range', '192.168.1.10', '192.168.1.19')
  -          if it would be useful to handle INT format IPv4 IPs, that's trivial to add.
-    all common comparators handled (including overlap and inclusion); new ones are trivial to add
-    easy human-readable and concise code (see below) for easy debugging and review
-    IP agnostic by default, or restrict to IPv4/IPv6, as needed.
-    all data validated and bad input detected
-    no issues expected with x32/x64, uses hex strings for comparisons so same code copes with both IPv4/IPv6, avoiding all INT_SIZE issues and any duplicated code between IPv4/IPv6 handlers.
- Code is a lot shorter, more 'generic', and easier to review than current approach (which tends to need 2 separate functions for IPv4/v6 and individual review of each for logic errors). The logic is very clean and trivial to enhance if a new data type, data format or comparison is later found to be useful.

It therefore provides in one function, back-end functionality of all existing ip_more/less_than, ip-in-subnet/range, and subnet/range-overlap/inclusion functions. Also, all input is validated, and IPv4/IPv6 agnostic (or restricted as desired).  So existing functions and high level code can use this as a high-level back end for comparison functions, simplifying use of high level IP functions.

The function is internally documented so here are examples of use as a back-end to other comparison functions:

<pre>function ip_in_subnet_ipv4_or_ipv6($ip, $subnet) {
   return ip_compare($ip, 'in', $subnet);
}

function ip_in_subnet_ipv4_only($ip, $subnet_ip, $subnet_bits) {
   return ip_compare($ip, 'in', array('subnet', $subnet_ip, $subnet_bits), 4);
}

function ip1_less_than_ip2($ip1, $ip2) {
   return ip_compare($ip1, '<', $ip2);
}

function ip1_less_than_ip2_ipv4_only($ip1, $ip2) {
   return ip_compare($ip1, '<', $ip2, 4);
}

function subnets_overlap($sn1, $sn2) {
   return ip_compare($sn1, 'overlaps', $sn2);
}

function range_disjoint_from_subnet($range_start, $range_end, $subnet_ip, $subnet_bits) {
   return ip_compare(array('range', $range_start, $range_end), '!overlaps', array('subnet', $subnet_ip, $subnet_bits));
}

function subnet_in_subnet_ipv6_only($subnet1, $subnet2) {
   return ip_compare($subnet1, 'included-in', $subnet2, 6);
}

function subnet_overlaps_range($subnet, $range) {
   return ip_compare($subnet, 'overlaps', $range);
}
</pre>

And some examples of actual code, taken from services_dhcp.php:

<pre>
(1)

if (!ip_in_subnet($_POST['gateway'], gen_subnet($parent_ip, $parent_sn) . "/" . $parent_sn) ...

EQUIVALENT:

if (!ip_compare($_POST['gateway'], 'in', array('subnet', $parent_ip, $parent_sn), 4) ...
</pre>

<pre>
(2)

$subnet_start = ip2ulong(long2ip32(ip2long($ifcfgip) & gen_subnet_mask_long($ifcfgsn)));
$subnet_end = ip2ulong(long2ip32(ip2long($ifcfgip) | (~gen_subnet_mask_long($ifcfgsn))));
if (ip2ulong($_POST['range_from']) > ip2ulong($_POST['range_to'])) {
    $input_errors[] = gettext("The range is invalid (first element higher than second element).");
}
if (ip2ulong($_POST['range_from']) < $subnet_start || ip2ulong($_POST['range_to']) > $subnet_end) {
    $input_errors[] = gettext("The specified range lies outside of the current subnet.");
}

EQUIVALENT:

if (!ip_compare(array('range', $_POST['range_from'], $_POST['range_to']), 'included-in', array('subnet', $ifcfgip, $ifcfgsn), 4)) {
    $input_errors[] = gettext("The specified range is mis-ordered or not within the current subnet.");
}
</pre>

<pre>
(3)

$dynsubnet_start = ip2ulong($_POST['range_from']);
$dynsubnet_end = ip2ulong($_POST['range_to']);
if (is_array($a_maps)) {
    foreach ($a_maps as $map) {
        if (empty($map['ipaddr'])) {
            continue;
        }
        if ((ip2ulong($map['ipaddr']) >= $dynsubnet_start) &&
            (ip2ulong($map['ipaddr']) <= $dynsubnet_end)) {
            $input_errors[] = sprintf(gettext("The DHCP range cannot overlap any static DHCP mappings."));
            break;
        }
    }
}
            
EQUIVALENT:

if (is_array($a_maps)) {
    foreach ($a_maps as $map) {
        if (!empty($map['ipaddr']) && ip_compare($map['ipaddr'], 'in', array('range', $_POST['range_from'], $_POST['range_to']), 4) {
            $input_errors[] = gettext("The DHCP range cannot overlap any static DHCP mappings.");
            break;
        }
    }
}
</pre>

### CODE REVIEW

**Comment by rbgarga** [comment]
@loos-br I would like to hear your thoughts about this one

**Comment by sbeaver-netgate** [comment]
Although this is useful work, it does not fix anything that is currently broken, and it would require a great deal of testing that realistically won't take place until after v 2.4

**Comment by jim-p** [comment]
In an effort to improve the tracking of changes and bug/feature requests, we have decided to require an entry on the [pfSense Redmine issue tracker](https://redmine.pfsense.org) associated with every pull request, and likewise the Redmine entry should also have a link back to the pull request.

If you could, please associate this PR to a Redmine issue either by locating an existing issue at https://redmine.pfsense.org or by creating a new issue. Add a link to the Redmine issue that points to this PR, and also add a link on the PR to the Redmine issue.

For more information, see https://doc.pfsense.org/index.php/Submitting_a_Pull_Request_via_Github

Thanks!

**Comment by rbgarga** [comment]
@loos-br can you comment about this change?

**Comment by sbeaver-netgate** [comment]
Since converting existing functionality to use this function now would incur significant risk, we are going to archive it for future use when new functionality is added that could benefit from it.

**Pull request closed without merging**
