### PR TITLE
Domeneshop DynDNS support. Implements #10826

### PR DESCRIPTION
**Pull request by vktg**
- [X] Redmine Issue: https://redmine.pfsense.org/issues/10826
- [X] Ready for review

Domeneshop is the largest registrar for .no (Norway) domains with over 40% of all .no domains. Source (in Norwegian): https://domene.shop/about
Their API is already added in ACME

https://api.domeneshop.no/docs/index.html#tag/ddns

### CODE REVIEW

**Comment by idarlund** [comment]
that was fast <3

**Comment by idarlund** [comment]
I've got a domain on Domeneshop. How can I help in testing this PR?

**Comment by vktg** [comment]
> I've got a domain on Domeneshop. How can I help in testing this PR?

You can install https://docs.netgate.com/pfsense/en/latest/development/system-patches.html and apply patch https://github.com/pfsense/pfsense/pull/4420/commits/4d6cc22309b4ec2b6cdec7d357507d607a45183a to test

**Comment by idarlund** [comment]
confirmed to be working on latest 2.5 development snapshot

**Comment by josteinh** [comment]
Working (on latest 2.5). It updates the address, but does not give green OK.
domeneshop

Also, If using both "Domeneshop" and "Domeneshop (v6)", the first one is overwritten by the last... :-(

**Comment by idarlund** [comment]
I'm getting similar behaviour:
image
We should create a bug report on redmine (https://redmine.pfsense.org/) and not continue on this merge request.

**Pull request merged**
