### PR TITLE
Tidy up "widgets"

### PR DESCRIPTION
**Pull request by ExolonDX**
Tidy up coding style
Tidy up SCRIPT and TH tags
Be consistent with quotes in HTML

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by jdillard** [comment]
Hey @ExolonDX,

It looks like your CLA has expired, so you will need to resign at the link above. CLAs were originally set to expire after one year, but they now last a lifetime (unless manually revoked) so this should be the last time you need to sign.

Thanks and I apologize for any inconvenience,

-- Jared

**Comment by ExolonDX** [comment]
Hello Jared, new CLA signed electronically.

**Comment by ExolonDX** [comment]
Closing pull request, too many changes have been made since this pull request was put together

**Pull request closed without merging**
