### PR TITLE
convert interfaces_* to fa

### PR DESCRIPTION
**Pull request by heper**
interfaces_vlan.php uses $_POST instead on $_GET.
no clue why that is. after some googling i found there is no real benefit in this scenario to use $_POST. (big chance i'm wrong)  

$_POST gave me an issue with the onclick js for act=del. (even when clicking cancel, the entry was deleted)
changed it to $_GET like every other similar page i've come across thus far.

### CODE REVIEW

**Comment by sbeaver-netgate** [comment]
There is a feature request in progress to turn all pages from GET to POST. The reasons being security and accidental actions when using the browser back button.

This proposal is OK for now, but I might change it back again :)

Steve
--
Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com | www.netgate.com

**Comment by sbeaver-netgate** [comment]
Actually I need you to revert the POST/GET change please and I will fix the immediate delete. The need to convert this page to POST was confirmed.

Steve
--
Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com | www.netgate.com

**Comment by heper** [comment]
@sbeaver-netgate 
gotcha, should be ok now.

**Comment by sbeaver-netgate** [comment]
Merged.

Thank you. I’ll look at the van_edit issue in a few minutes.

Steve
--
Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com | www.netgate.com

**Comment by sbeaver-netgate** [comment]
Confirm deletion fixed in a5855731c0276b72585c3a23378c85370f7ebf33

**Pull request merged**
