### PR TITLE
Allow import of PKCS12 (pfx) certificates

### PR DESCRIPTION
**Pull request by miken32**
- [x] Redmine Issue: https://redmine.pfsense.org/issues/8645
- [x] Ready for review

Allows user to select a PKCS #12 certificate store to import a certificate. Optionally allows for import of bundled intermediate certificates. Tested with a couple of different certificates.

### CODE REVIEW

**Comment by miken32** [comment]
Annoyances: the browser prompts to save password, and the system will allow import of duplicate CAs.

**Comment by jim-p** [comment]
Not much can be done about the browser password, unfortunately. Browsers have decided that web pages can't be trusted to tell them what fields they shouldn't save, so traditional controls to tell them not to auto-fill are ignored these days.

The duplicate CA issue could be solved by checking existing CAs and comparing the subject/serial/etc. Even a basic check using `lookup_ca_by_subject()` and seeing if anything is found should solve most cases.

Though this PR looks OK, it conflicts with another open PR, #4062 -- Depending on which one is accepted first, the other will need fixed to accommodate the changes of the other.

**Comment by miken32** [comment]
I thought about checking the subject, but that's not enough, so serial number would probably need to be checked as well. Ideally these checks would be in a centralized place so that duplicate CAs and certs can't be imported anywhere. I'm not crazy about the way `import_ca()` works (modifying by reference and never returning anything useful) because it makes this more difficult than it should be.

Happy to work around the changes in the other PR if it comes to that.

**Comment by miken32** [comment]
Updated checks; duplicates were not imported during my testing.

Re password field, I'd propose that it doesn't need to be a password field at all. The only thing a password field prevents is shoulder surfing; given this is an administrative backend to manage a system and not a login page, the security implications for almost any user would be negligible. I don't expect anyone to agree with me though.

**Comment by jim-p** [comment]
Closing in favor of #4175

**Pull request closed without merging**
