### PR TITLE
Feature #8123: Add GoDaddy as a Dynamic DNS provider

### PR DESCRIPTION
**Pull request by LedPighp**

### CODE REVIEW

**Comment by LedPighp** [comment]
I've added support for registering A and AAAA records with GoDaddy. I did not implement MX records as it would require using a different API which replaces all records on a hostname. This would prevent having IPv4 and IPv6 registered at the same time.

**Comment by huseman21** [comment]
I can't seem to get it to work, I assume things changed.  when I test the patch this is the results.

/usr/bin/patch --directory=/ -t -p2 -i /var/patches/5a78946eae35a.patch --check --forward --ignore-whitespace

Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|From 456ba14f299fa197b348505caea53a0fe7c092cb Mon Sep 17 00:00:00 2001
|From: Sam Neely 
|Date: Thu, 23 Nov 2017 17:23:23 -0800
|Subject: [PATCH] Feature #8123: Add GoDaddy as a Dynamic DNS provider
|
|---
| src/etc/inc/dyndns.class                   | 51 ++++++++++++++++++++++++++++++
| src/etc/inc/globals.inc                    |  2 +-
| src/etc/inc/services.inc                   |  4 +--
| src/usr/local/www/services_dyndns_edit.php | 19 ++++++++++-
| 4 files changed, 72 insertions(+), 4 deletions(-)
|
|diff --git a/src/etc/inc/dyndns.class b/src/etc/inc/dyndns.class
|index 5241173ad5..e8d7534ebb 100644
|--- a/src/etc/inc/dyndns.class
|+++ b/src/etc/inc/dyndns.class
--------------------------
Patching file etc/inc/dyndns.class using Plan A...
Hunk #1 failed at 63.
Hunk #2 failed at 121.
Hunk #3 failed at 232.
Hunk #4 succeeded at 248 (offset -9 lines).
Hunk #5 succeeded at 343 with fuzz 2 (offset -1 lines).
Hunk #6 succeeded at 812 (offset -9 lines).
Hunk #7 succeeded at 1695 (offset -31 lines).
3 out of 7 hunks failed while patching etc/inc/dyndns.class
Hmm...  The next patch looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/src/etc/inc/globals.inc b/src/etc/inc/globals.inc
|index 56ba52e962..304bfee7f3 100644
|--- a/src/etc/inc/globals.inc
|+++ b/src/etc/inc/globals.inc
--------------------------
Patching file etc/inc/globals.inc using Plan A...
Hunk #1 succeeded at 205 with fuzz 2 (offset -2 lines).
Hmm...  The next patch looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/src/etc/inc/services.inc b/src/etc/inc/services.inc
|index 76ddc10148..f1a1c0277a 100644
|--- a/src/etc/inc/services.inc
|+++ b/src/etc/inc/services.inc
--------------------------
Patching file etc/inc/services.inc using Plan A...
Hunk #1 failed at 23.
1 out of 1 hunks failed while patching etc/inc/services.inc
Hmm...  The next patch looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/src/usr/local/www/services_dyndns_edit.php b/src/usr/local/www/services_dyndns_edit.php
|index 2d26176f8d..c43f1fca4e 100644
|--- a/src/usr/local/www/services_dyndns_edit.php
|+++ b/src/usr/local/www/services_dyndns_edit.php
--------------------------
Patching file usr/local/www/services_dyndns_edit.php using Plan A...
Hunk #1 failed at 299.
Hunk #2 succeeded at 358.
Hunk #3 succeeded at 371.
Hunk #4 succeeded at 519 (offset -14 lines).
1 out of 4 hunks failed while patching usr/local/www/services_dyndns_edit.php
done

**Comment by LedPighp** [comment]
huseman21,

I verified that this patch does install properly on with a fresh install of pfSense. Here are the steps I followed:

1. Instaled pfSense 2.4.2 on a freshly formatted system.
2. After installing, immediately upgrade to 2.4.2_p1
3. Install the System Patches package
4. Added a new patch for GoDaddy:
    - Description: GoDaddy
    - URL/Commit ID: https://github.com/pfsense/pfsense/pull/3875.patch
    - Path Strip Count: 2
    - All other fields left blank / set to the default value
    - Saved the patch
5. Pressed Fetch
6. Pressed Test to verify that the patch would apply. The information box said that it could be applied cleanly but it could not be reverted cleanly
7. Pressed Apply

At this point, GoDaddy was present in Dynamic DNS clients list.

**Comment by jim-p** [comment]
Redmine issue: https://redmine.pfsense.org/issues/8123

**Pull request merged**
