### PR TITLE
UI Tests for PfSense

### PR DESCRIPTION
**Pull request by individual-it**
This implements UI tests for pfSense
The tests are based on phpunit and selenium and run on https://travis-ci.org and https://saucelabs.com

1. travis-ci downloads and boots an image of pfsense in qemu
2. pfsense is updated by `pfSense-upgrade -d -y` & `pfSsh.php playback gitsync master`
3. tests are run against the upgraded pfsense using selenium on saucelabs

How to run this tests locally:

1. download Selenium standalone server jar from http://docs.seleniumhq.org/download/
2. download the chromedriver from: https://sites.google.com/a/chromium.org/chromedriver/ and place it in the same folder as the selenium server
3. start selenium:`java -jar selenium-server-standalone-3.0.1.jar`
4. set the 3 environment variables: SRV_HOST_NAME, SRV_HOST_URL and SRV_HOST_PORT to wherever your dev. environment runs e.g.:
```
export SRV_HOST_NAME=localhost
export SRV_HOST_URL=pfsense
export SRV_HOST_PORT=80
```
5. install php composer:
```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '55d6ead61b29c7bdee5cccfb50076874187bd9f21f65d8991d46ec5cc90518f447387fb9f76ebae1fbbacf329e583e30') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
```
6. install composer dependencies: `php composer.phar install`
7. run tests: `vendor/bin/phpunit -c tests/phpunit-selenium-autotest.xml`

test view on travis: https://travis-ci.org/individual-it/pfsense/builds/202541766
test view on saucelabs: https://saucelabs.com/beta/tests/b3085d9422cb49bdac8f19d0d3550581

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by phil-davis** [comment]
This demonstrates how front-end GUI tests could be done for pfSense. Some of the challenges are:
1) pfSense is on FreeBSD, whereas Travis-CI has only Linux and OSX environments. So the pfSense software under test has to be run inside a VM that runs FreeBSD/pfSense.
2) How to get a "current build/snapshot" of pfSense to run the tests against. In this first implementation it starts with some snapshot from some (recent) time on master that has been pre-installed into a VM. Then it does a pfSense-upgrade on that to get it to the latest snapshot. That will get binaries from any quite-recent changes into the upgraded VM. Then it does a gitsync of master, which will pull in current commits to master. So it can test any script changes (PHP, JS, bash...) from the current master, but if there are binaries that need to be recompiled then it needs to wait for the snapshot builder.
3) Even if there was a native Travis-CI FreeBSD environment, doing a whole build from scratch would be a challenge - time taken to build over-and-over for every little change, the build products then need to be deployed into a separate system (pfSense is not some little piece of application software that can just be easily run on the build machine once the build is done)...

Things needed:
a) When Travis-CI runs on a branch of a repo, or a pull request, it automagically fetches the code from that repo or PR into the Travis-CI VM, but that is not where we will run the code. In order to automatically pre-test other branches and PRs, the pfSense gitsync that is done in the FreeBSD VM needs to gitsync with the branch/PR that Travis knows it is testing.
b) Get a pre-installed starting image from a well-known place (at the moment @individual-it has made one himself that is loaded), or get the latest installer from in https://snapshots.pfsense.org/ and run a default installation from it to the VM.
c) Setup Travis-CI and Sauce accounts linked to the pfSense GitHub account, so that automated tests can run from the official pfSense repo.

**Comment by individual-it** [comment]
The last commit solves "Things needed a)"
The code gets copied from travis-ci into the pfsense VM by scp and the gitsync uses this code. 
That way we do not have to sync twice with github and also PRs can be tested. This applies only to PRs from the same repro. So if this would be implemented in pfsense PRs comming from a branch in https://github.com/pfsense/pfsense would be tested.
PRs from foreign forks cannot be tested because they do not have access
to the saucelabs username/key

**Comment by phil-davis** [comment]
A few examples of recent front-end bugs that [could|should] have been caught by front-end testing of actions:
https://github.com/pfsense/pfsense/commit/27d15a216fcc86cbeef4db4ced518438fc07378d
https://github.com/pfsense/pfsense/commit/12e3e735d8e0f6f0256175ad73f07a9fd196d1e9
https://github.com/pfsense/pfsense/commit/d54107b1b16ecb3f0c9b3da4fce85a220f7a12c0

**Comment by jim-p** [comment]
In an effort to improve the tracking of changes and bug/feature requests, we have decided to require an entry on the [pfSense Redmine issue tracker](https://redmine.pfsense.org) associated with every pull request, and likewise the Redmine entry should also have a link back to the pull request.

If you could, please associate this PR to a Redmine issue either by locating an existing issue at https://redmine.pfsense.org or by creating a new issue. Add a link to the Redmine issue that points to this PR, and also add a link on the PR to the Redmine issue.

For more information, see https://doc.pfsense.org/index.php/Submitting_a_Pull_Request_via_Github

Thanks!

**Comment by phil-davis** [comment]
Is there any interest in automated CI?
(any combinations of "unit testing", "API testing" and "UI testing" depending on what well-defined "units" and "API" can be found)

**Comment by sbeaver-netgate** [comment]
This work should be moved to its own, new repo. WIll investigate that ASAP

**Comment by sbeaver-netgate** [comment]
A new repo has been created here. Would it be possible to to push your code to that repo, rather than merging it into the pfSense code base?

**Comment by phil-davis** [comment]
@sbeaver-netgate I don't see that repo online - maybe it has not been published, or is marked private or?

**Comment by sbeaver-netgate** [comment]
I seem to lack the power to make it public. Let me see if I can locate a colleague with that privilege.

**Comment by sbeaver-netgate** [comment]
Should be public now

**Comment by rbgarga** [comment]
Please re-submit to https://github.com/pfsense/UI-Automated-Testing repo. thanks!

**Pull request closed without merging**
