### PR TITLE
OpenVPN copy auth_pass. Fixes #10703

### PR DESCRIPTION
**Pull request by vktg**
- [X] Redmine Issue: https://redmine.pfsense.org/issues/10703
- [X] Ready for review

Fixes copying `auth_pass` and `proxy_passwd` with copy/clone button

### CODE REVIEW

**Comment by vktg** [comment]
Updated
Now `addPassword()` may not show the password confirm field
`auth_pass` and `proxy_passwd` copied successfully

**Comment by valadas** [comment]
Interesting, I have been chasing an issue where pfSense would not appear to boot after a power loss. I had to plug a monitor and keyboard physically on the machine (no web UI) to figure out that OpenVPN was asking for a password and waiting for one to complete the boot process...

**Comment by vktg** [comment]
> Interesting, I have been chasing an issue where pfSense would not appear to boot after a power loss. I had to plug a monitor and keyboard physically on the machine (no web UI) to figure out that OpenVPN was asking for a password and waiting for one to complete the boot process...

Please see https://redmine.pfsense.org/issues/10409

**Comment by valadas** [comment]
>Please see https://redmine.pfsense.org/issues/10409

Oh, thanks @vktg

**Pull request merged**
