### PR TITLE
[#4542] Add RFC 4638 client support (PPPoE MTU > 1492)

### PR DESCRIPTION
**Pull request by davidjwood**
[Redmine #4542](https://redmine.pfsense.org/issues/4542)

**Requires:** pfsense/FreeBSD-ports#1 (mpd5 support for PPP-Max-Payload).

This patch adds [RFC 4638](https://tools.ietf.org/html/rfc4638) client support to pfSense, allowing operation with PPPoE MTU > 1492. As PPPoE has an 8 byte overhead, this requires jumbo frame support on the parent interface(s) of the PPPoE ports.

# Typical usage scenario for MTU 1500 operation

* Interfaces -> *PPPoE interface* (usually WAN)
* enter 1500 in 'MTU'
* press 'Save'

# Approach taken

## PPPoE MTU handling and Principle of Least Astonishment considerations

The PPPoE MTU for a port is:
* the MTU configured for the port
    * Interfaces -> (assign)
    * PPP tab
    * press 'e' next to the PPP interface in question
    * press 'Show Advanced Options'
    * enter a value in 'MTU' in the 'Link parameters' section
    * press 'Save'
* if no MTU is configured for the port, the MTU configured for the PPPoE interface (**typical usage scenario**)
    * Interfaces -> *PPPoE interface*
    * enter a value in 'MTU'
    * press 'Save'
* if no MTU is configured for the port or the PPPoE interface, the PPPoE default of 1492 is used.

The code attempts to set the MTU of each port's parent interface of each port to 8 higher than the port's configured MTU. If the port's parent interface is a VLAN, the code attempts to ensure the MTU of the physical interface is at least 8 higher than the port's configured MTU so that the VLAN MTU can be set to 8 higher than the port's configured MTU.

Explicitly configured interface MTUs are respected.

The code ensures the MTU of VLANs does not rise above 1500 without explicit configuration of an MTU > 1500, preventing a Principle of Least Astonishment breach if there is a PPPoE port parent interface VLAN and other VLANs on the same physical interface.

When building the PPPoE configuration, the code checks the MTU of each port's parent interface and configures the MTU of the port to be the configured port MTU or 8 lower than the interface MTU, whichever is the lower.

# Common scenarios

## No explicit PPPoE MTU is configured

pfSense assumes the PPPoE default MTU of 1492.

## User configures the PPPoE interface MTU to 1500, PPPoE parent interface port supports MTU 1508 operation

pfSense will attempt to negotiate a 1500 byte maximum PPPoE payload with the ISP.

## User configures the PPPoE interface MTU to 1500, PPPoE parent interface port supports a maximum MTU of 1500

pfSense silently falls back to PPPoE MTU 1492 operation.

# Testing

A version of this patch on top of 2.2.4-RELEASE has been [tested by some forum users](https://forum.pfsense.org/index.php?topic=100219.0) and is running in production at my site.

### CODE REVIEW

**Comment by davidjwood** [comment]
@loos-br I understand the Redmine bug is allocated to you.

**Comment by rbgarga** [comment]
@cbuechler did you have a chance to test this one?

**Comment by davidjwood** [comment]
@cbuechler I know things are extremely busy at present with the ongoing work on 2.3. Is there any hope of getting this reviewed and integrated before 2.3 enters the beta phase? Is there anything I can do to help this process?

Congratulations for all the pfSense team have achived in 2015. I wish you well at this festive time.

**Comment by davidjwood** [comment]
@cbuechler @rbgarga I've just fixed a conflict with master.

Is the current strategy to QA existing code and not merge new features? If there is a moratorium on merging new features, it's probably best that I stop wasting time on this until the moratorium is lifted.

**Comment by cbuechler** [comment]
This tested out fine and has been merged. @davidjwood please verify in snapshots since you have a real world connection. Thanks!

**Comment by davidjwood** [comment]
@cbuechler Tested and confirmed working in 2.3.a.20160105.0829 on amd64 (full install in a VM).

PPP log output (with personally identifying information censored):

	Jan  5 16:43:05 pfsense-test ppp: Multi-link PPP daemon for FreeBSD
	Jan  5 16:43:05 pfsense-test ppp:  
	Jan  5 16:43:05 pfsense-test ppp: process 6464 started, version 5.7 (root@pfSense_master_amd64_amd64-pfSense_master-job-01 19:14 31-Dec-2015)
	Jan  5 16:43:05 pfsense-test ppp: web: web is not running
	Jan  5 16:43:05 pfsense-test ppp: [opt2] Bundle: Interface ng0 created
	Jan  5 16:43:05 pfsense-test ppp: [opt2_link0] Link: OPEN event
	Jan  5 16:43:05 pfsense-test ppp: [opt2_link0] LCP: Open event
	Jan  5 16:43:05 pfsense-test ppp: [opt2_link0] LCP: state change Initial --> Starting
	Jan  5 16:43:05 pfsense-test ppp: [opt2_link0] LCP: LayerStart
	Jan  5 16:43:05 pfsense-test ppp: [opt2_link0] PPPoE: Set PPP-Max-Payload to '1500'
	Jan  5 16:43:05 pfsense-test ppp: [opt2_link0] PPPoE: Connecting to ''
	Jan  5 16:43:05 pfsense-test ppp: PPPoE: rec'd ACNAME "dsl7.th-lon-XXXXXXXXXXXXXX"
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0] PPPoE: rec'd PPP-Max-Payload '1500'
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0] PPPoE: connection successful
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0] Link: UP event
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0] LCP: Up event
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0] LCP: state change Starting --> Req-Sent
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0] LCP: SendConfigReq #1
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0]   MRU 1500
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0]   MAGICNUM 8fde3f40
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0] LCP: rec'd Configure Request #70 (Req-Sent)
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0]   MRU 1500
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0]   AUTHPROTO CHAP MD5
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0]   MAGICNUM 774588a8
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0] LCP: SendConfigAck #70
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0]   MRU 1500
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0]   AUTHPROTO CHAP MD5
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0]   MAGICNUM 774588a8
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0] LCP: state change Req-Sent --> Ack-Sent
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0] LCP: rec'd Configure Ack #1 (Ack-Sent)
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0]   MRU 1500
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0]   MAGICNUM 8fde3f40
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0] LCP: state change Ack-Sent --> Opened
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0] LCP: auth: peer wants CHAP, I want nothing
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0] LCP: LayerUp
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0] CHAP: rec'd CHALLENGE #1 len: 32
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0]   Name: "dsl7.th-lon"
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0] CHAP: Using authname "zenXXXXX@zen"
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0] CHAP: sending RESPONSE #1 len: 33
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0] CHAP: rec'd SUCCESS #1 len: 40
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0]   MESG: CHAP authentication success, unit 32
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0] LCP: authorization successful
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0] Link: Matched action 'bundle "opt2" ""'
	Jan  5 16:43:06 pfsense-test ppp: [opt2_link0] Link: Join bundle "opt2"
	Jan  5 16:43:06 pfsense-test ppp: [opt2] Bundle: Status update: up 1 link, total bandwidth 64000 bps
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPCP: Open event
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPCP: state change Initial --> Starting
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPCP: LayerStart
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPV6CP: Open event
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPV6CP: state change Initial --> Starting
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPV6CP: LayerStart
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPCP: Up event
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPCP: state change Starting --> Req-Sent
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPCP: SendConfigReq #1
	Jan  5 16:43:06 pfsense-test ppp: [opt2]   IPADDR 0.0.0.0
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPV6CP: Up event
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPV6CP: state change Starting --> Req-Sent
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPV6CP: SendConfigReq #1
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPCP: rec'd Configure Request #53 (Req-Sent)
	Jan  5 16:43:06 pfsense-test ppp: [opt2]   IPADDR 62.3.84.27
	Jan  5 16:43:06 pfsense-test ppp: [opt2]     62.3.84.27 is OK
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPCP: SendConfigAck #53
	Jan  5 16:43:06 pfsense-test ppp: [opt2]   IPADDR 62.3.84.27
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPCP: state change Req-Sent --> Ack-Sent
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPCP: rec'd Configure Nak #1 (Ack-Sent)
	Jan  5 16:43:06 pfsense-test ppp: [opt2]   IPADDR a.b.c.d
	Jan  5 16:43:06 pfsense-test ppp: [opt2]     a.b.c.d is OK
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPCP: SendConfigReq #2
	Jan  5 16:43:06 pfsense-test ppp: [opt2]   IPADDR a.b.c.d
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPV6CP: rec'd Configure Request #194 (Req-Sent)
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPV6CP: SendConfigAck #194
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPV6CP: state change Req-Sent --> Ack-Sent
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPV6CP: rec'd Configure Ack #1 (Ack-Sent)
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPV6CP: state change Ack-Sent --> Opened
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPV6CP: LayerUp
	Jan  5 16:43:06 pfsense-test ppp: [opt2]   aaaa:bbbb:cccc:dddd -> 0230:88ff:fe16:5eff
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IFACE: Up event
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IFACE: Rename interface ng0 to pppoe
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPCP: rec'd Configure Ack #2 (Ack-Sent)
	Jan  5 16:43:06 pfsense-test ppp: [opt2]   IPADDR a.b.c.d
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPCP: state change Ack-Sent --> Opened
	Jan  5 16:43:06 pfsense-test ppp: [opt2] IPCP: LayerUp
	Jan  5 16:43:06 pfsense-test ppp: [opt2]   a.b.c.d -> 62.3.84.27

**Pull request merged**
