### PR TITLE
Revert previous commit which obsoleted fend.inc

### PR DESCRIPTION
**Pull request by doktornotor**
Reason: https://github.com/pfsense/FreeBSD-ports/search?utf8=%E2%9C%93&q=fend.inc

https://forum.pfsense.org/index.php?topic=103449.0

### CODE REVIEW

**Comment by rbgarga** [comment]
Since we are in ALPHA state and packages need to be converted to bootstrap I vote to change entries in FreeBSD-ports repo (pfSense-packages is not relevant for 2.3) to include foot.inc and stop syncing packages changes using script. @jim-p already started to convert some packages to bootstrap and it's time to separate both repos anyway. What do you think @sbeaver-netgate, @jim-p and @cbuechler ?

**Comment by sbeaver-netgate** [comment]
I assumed that @jim-p was converting the "built-in" packages that ESF kind-of maintains. Conversion is underway elsewhere for snort, suricata, pfblockerng etc. There are other packages that would run the risk of becoming orphaned though right? So do we retain those packages that (by virtue of older styling) are ugly to the point of being almost useless, or ditch them until converted?

**Comment by sbeaver-netgate** [comment]
I'll merge this for now pending further discussion.

**Comment by jim-p** [comment]
The ones I'm converting are among those we maintain internally (though not built in, they are "ours"). The other packages may need to be adjusted on a case-by-case basis. I know some are being converted by their maintainers (like snort/suricata, for one) others may be on us to convert as well. If we can gain some ground by replacing just the foot.inc lines that would be good. Any more significant changes should probably be cleared by the maintainers first.

@rbgarga It is probably time to run one last sync and then break the automatic updating so more focus is put on fixing 2.3 packages.

**Comment by sbeaver-netgate** [comment]
If we just replace fend.inc with foot.inc, then delete the line:

<body link="#0000CC" vlink="#0000CC" alink="#0000CC">

from each package web page, they will become usable, if not exactly attractive.

**Comment by doktornotor** [comment]
If someone has time to run some sed on package's PHP files to do the above, then yeah, do it and just stop syncing those after that and call it a day. I'm pretty much done with fixing of random broken stuff for RELENG_2_2 anyway, what hasn't been fixed by now is simply broken code that people don't want to touch by 10ft pole. 

The goal here is merely to prevent pointlessly breaking things that were NOT broken yet.

(And, I'd appreciate some page with links to the package directories for the packages that made it to 2.3 ports repo. Since the repo structure seriously drives me nuts.)

**Comment by jim-p** [comment]
I can whip up a wiki doc for the packages, here is what is in the repo currently:
```
~/devel/freebsd-ports (devel)$ ls -d */pfSense-pkg* 
benchmarks/pfSense-pkg-iperf         net/pfSense-pkg-LADVD                       sysutils/pfSense-pkg-Backup
emulators/pfSense-pkg-Open-VM-Tools  net/pfSense-pkg-mtr-nox11                   sysutils/pfSense-pkg-blinkled
ftp/pfSense-pkg-FTP_Client_Proxy     net/pfSense-pkg-ntopng                      sysutils/pfSense-pkg-Cron
mail/pfSense-pkg-mailreport          net/pfSense-pkg-OpenBGPD                    sysutils/pfSense-pkg-gwled
net-mgmt/pfSense-pkg-darkstat        net/pfSense-pkg-pfBlockerNG                 sysutils/pfSense-pkg-Notes
net-mgmt/pfSense-pkg-iftop           net/pfSense-pkg-Quagga_OSPF                 sysutils/pfSense-pkg-RRD_Summary
net-mgmt/pfSense-pkg-softflowd       net/pfSense-pkg-routed                      sysutils/pfSense-pkg-Service_Watchdog
net-mgmt/pfSense-pkg-zabbix-agent    net/pfSense-pkg-siproxd                     sysutils/pfSense-pkg-Shellcmd
net-mgmt/pfSense-pkg-zabbix-proxy    security/pfSense-pkg-nmap                   sysutils/pfSense-pkg-syslog-ng
net/pfSense-pkg-arping               security/pfSense-pkg-openvpn-client-export  sysutils/pfSense-pkg-System_Patches
net/pfSense-pkg-Avahi                security/pfSense-pkg-snort                  www/pfSense-pkg-Lightsquid
net/pfSense-pkg-freeradius2          security/pfSense-pkg-sudo                   www/pfSense-pkg-squid
net/pfSense-pkg-haproxy              security/pfSense-pkg-suricata               www/pfSense-pkg-squidGuard
net/pfSense-pkg-haproxy-devel        sysutils/pfSense-pkg-AutoConfigBackup
```

**Comment by doktornotor** [comment]
>  can whip up a wiki doc for the packages

Yes, please :) (Thanks for the list, that's helpful as well.)

**Comment by jim-p** [comment]
Here you go: https://doc.pfsense.org/index.php/Package_Port_List
And: https://doc.pfsense.org/index.php/Package_Port_Directory_Structure

I've got more notes ready to go into more docs but they need more work yet before they're suitable for general consumption.

**Comment by doktornotor** [comment]
Awesome, thanks.

**Comment by rbgarga** [comment]
Commit was reverted

**Pull request closed without merging**
