### PR TITLE
Update system_camanager.php

### PR DESCRIPTION
**Pull request by xbipin**
Make title color more consistent with other pages.
Improving aesthetics.

### CODE REVIEW

**Comment by rbgarga** [comment]
Feel free to send one pull request changing it on all necessary pages, I'll merge the ones you sent

**Comment by rbgarga** [comment]
In order to get patches applied you must sign Individual or Corporate CLA as described at https://www.pfsense.org/about-pfsense/#legal

**Comment by xbipin** [comment]
ok sorry, im new to github etc so just figuring things out, i have singed the CLA

**Comment by rbgarga** [comment]
You could keep those one you already opened, it was just a suggestion for next ones. Now since you already closed, I'll wait the new one. Thanks for contributing!

**Comment by xbipin** [comment]
im a little confused on this github thing, do i need to clone pfsense repo and work on that or can i simply work on the pfsense report and submit changes there?

**Comment by rbgarga** [comment]
Usually the workflow is:

* Create a fork of pfSense repo
* Clone your fork
* Create a new branch for each Pull Request you want to send (or for each task you want to talk)
* Make the changes on that branch
* Commit it
* Push the new branch to your fork
* Open a pull request

You can find information about how to keep your fork up to date and how to send pull requests at:

https://help.github.com/articles/syncing-a-fork/
https://help.github.com/articles/using-pull-requests/

**Pull request closed without merging**
