### PR TITLE
Fix #5252 Preserve alias when editing an existing rule

### PR DESCRIPTION
**Pull request by phil-davis**
and default src and dst to any when creating a new rule.

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by doktornotor** [comment]
1/ The CLA script is clearly still broken.
2/ The "we cannot be bothered with braces in singleline if/else is a disaster in itself.

**Comment by sbeaver-netgate** [comment]
Merged. Thank you!

**Comment by ariyako** [comment]
nice!

**Pull request merged**
