### PR TITLE
Order DNS provider instructions alphabetically

### PR DESCRIPTION
**Pull request by Bojan023**
Hi! I stumbled upon the weird order of these instructions a couple of times meanwhile, I think it makes sense to order them alphabetically.

- [x] Redmine Issue: minor textual change, so none
- [x] Ready for review

### CODE REVIEW

**Review by jim-p — CHANGES_REQUESTED** [review]
Several lines have a mix of leading tabs and spaces, when it should be tabs only. They are easy to see here in the diff here on GitHub.

**Comment by Bojan023** [comment]
You are right, no idea how these slipped into the initial commit. Fixed by last commit!

**Comment by Bojan023** [comment]
Good find, no idea how these slipped into the commit.. Fixed!

**Comment by Bojan023** [comment]
@jim-p can you check this PR? Thanks.

**Review by rbgarga — CHANGES_REQUESTED** [review]
@Bojan023 you are sorting items but you are also renaming Route53 to Azure in the same commit.  Could you please split it into 2 different requests?

**Pull request closed without merging**
