### PR TITLE
Add security notes for privilege assignment pages

### PR DESCRIPTION
**Pull request by phil-davis**
Suggested solution for Redmine 2247

### CODE REVIEW

**Comment by stilez** [comment]
Roughly right. Will look more in a bit.

**Comment by rbgarga** [comment]
Please rebase

**Comment by phil-davis** [comment]
I did something weird in my git rebase - it is showing all the commits from master that have happened since I did the code. I was expecting to just see my changes, but now branched off the current head of master.

**Comment by rbgarga** [comment]
Yeah, something went wrong here. Can you re-submit?

**Comment by phil-davis** [comment]
Resubmitted as #3341

**Pull request closed without merging**
