### PR TITLE
Removed redundant if statement part

### PR DESCRIPTION
**Pull request by Fusl**

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by cbuechler** [comment]
That's not redundant. It prevents use of a gateway with synproxy state rules because it isn't functional in that circumstance (or at least didn't used to be, have you seen otherwise?). This is wrong regardless though as it would make it impossible to save any firewall rule that specified a gateway, which breaks tons of things.

**Comment by Fusl** [comment]
Of course this is redundant, please take a look here:

https://github.com/pfsense/pfsense/pull/2876/commits/d19ad3c23a4461cde5dc74ddc9e4dcf20b010655#diff-34254bd85b68c71eddb8fc0eed510e66L455

You have the exact same if statement in line 455.

**Comment by cbuechler** [comment]
I didn't notice the check above it, looked like you just made a change without having any idea of why. I'll remove it. Thanks

**Comment by cbuechler** [comment]
Fixed in 34515250ca726f096071b139fcebd5d18601162a, thanks @Fusl

**Pull request closed without merging**
