### PR TITLE
Flush link-local IPs when configuring track interface

### PR DESCRIPTION
**Pull request by k-paulius**
Fixes #6317. See RM for details.

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by k-paulius** [comment]
I signed CLA again.

**Comment by cbuechler** [comment]
Thanks @k-paulius. Not sure this won't create regressions in other circumstances, needs review post-2.3.1.

**Comment by cbuechler** [comment]
Works and doesn't introduce any regressions. Merged to master and 2.3.2. Thanks @k-paulius !

**Pull request merged**
