### PR TITLE
gateways, put user back in control of gateway order / precedence

### PR DESCRIPTION
**Pull request by PiBa-NL**
- [x] Redmine Issue: https://redmine.pfsense.org/issues/8910
- [x] Ready for review

### CODE REVIEW

**Comment by jim-p** [comment]
Copying my question here from the Redmine ticket:
> Why would that matter now? What loss of functionality is there? You can select it specifically, or setup a gateway group with it on Tier 1.
>
> Not selecting WAN by default was breaking a number of people in unexpected ways based on whether or not another interface with a gateway came before WAN alphabetically.

I'm not seeing what this PR would solve. It's entirely possible I'm overlooking it though. I just need some clarification on what the problem is an the intended effect of this will be.

**Comment by PiBa-NL** [comment]
Thanks jim-p, reply added in redmine.

**Comment by sbeaver-netgate** [comment]
Apparently no longer required. Please resubmit if still required.

**Comment by sbeaver-netgate** [comment]
No longer required

**Pull request closed without merging**
