### PR TITLE
Fixed typo in lifetime validation

### PR DESCRIPTION
**Pull request by seyfidin**
- [x] Redmine Issue: https://redmine.pfsense.org/issues/12159
- [x] Ready for review

### CODE REVIEW

**Review by jim-p — CHANGES_REQUESTED** [review]
This looks OK but needs a Redmine entry.

To effectively track changes and bug/feature requests, we require an entry on the [pfSense Redmine issue tracker](https://redmine.pfsense.org) associated with every pull request, and likewise the Redmine entry should also have a link back to the pull request.

Please associate this PR to a Redmine issue either by locating an existing issue at https://redmine.pfsense.org or by creating a new issue. Add a link to the Redmine issue that points to this PR, and also add a link on the PR to the Redmine issue.

For more information, see https://docs.netgate.com/pfsense/en/latest/development/pull-request.html
Thanks!

**Comment by seyfidin** [comment]
The page for submitting pull request states that minor typos are excepted from having redmine tickets. This is really a very minor typo, nothing else was touched. Are you sure a redmine ticket is needed for this?

**Comment by jim-p** [comment]
This is a bug in functionality and not a typo in the sense the guide meant. The guide was referring to user-visible text/language typos that don't affect functionality.

That said, we're changing things slightly but that guide hasn't been updated yet. We're trying to get to a point where every commit has a Redmine issue associated with it, even minor ones.

**Comment by seyfidin** [comment]
Makes sense, I just added the redmine ticket

**Review by jim-p — APPROVED** [review]

**Pull request merged**
