### PR TITLE
Packet Capture: add preview results

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**
- allow preview results while a capture is still running
- add a capture summary field
- count: if empty value, properly set it to default 100 instead of 0
- do not pass empty argument to tcpdump when no filter options are posted
- do not check form validity when clicking other buttons than start
- more compact GUI (spannable help tool tips)
- info changes and fixes

- [X] Redmine Issue: https://redmine.pfsense.org/issues/13017
- [X] Ready for review

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
@jim-p 
In the redmine page, I added a patch that applies to the current master branch if it is easier to test/review

**Comment by crawc** [comment]
I found an issue while testing that  I'll comment on...

If you have no OpenVPN servers/clients you get an error on line 171:
`	if (is_array($config['openvpn']["openvpn-{$mode}"])) {` 
Since `$config['openvpn']` is a sting, not an array. I found that if you change it to just...
`	if (is_array($config['openvpn'])) {`
It works as desired.

**Comment by PhilZ-cwm6** [comment]
Fixing it will depend on the fact that devs are interested or not into merging it

**Comment by marcos-ng** [comment]
Implemented with https://redmine.pfsense.org/issues/13382

**Pull request closed without merging**
