### PR TITLE
Fix reboot prompt on RAM Disk configuration change

### PR DESCRIPTION
**Pull request by nazar-pc**
There was a way to avoid getting reboot prompt on changing RAM Disk option by submitting form with errors first and re-submitting it later.
This was fixed and other tweaks were made, commit message describes it all well.

I hope my changes make sense and are actually reducing complexity as well as improve readability like I think they do.

### CODE REVIEW

**Comment by nazar-pc** [comment]
Is anyone reviewing PRs here?

**Comment by nazar-pc** [comment]
What else is needed to get this merged?

**Comment by nazar-pc** [comment]
Over 5 months this PR is open without any complains whatsoever. And in fresh release notes you encourage to contribute to your project. How can anyone contribute if it takes so long to merge anything?

**Comment by sbeaver-netgate** [comment]
Awaiting review

**Pull request merged**
