### PR TITLE
Convert fonts to woff2

### PR DESCRIPTION
**Pull request by GChuf**
- [x] Ready for review
- [x] Redmine issue: https://redmine.pfsense.org/issues/11507 

I can also add woff files if needed (for [support on IE9-11](https://caniuse.com/woff2)), but for now I only added woff2 in hopes that sysadmins use better browsers than IE11 in 2021.
Files were converted with _woff2_compress_ tool (lossless compression / installed through _apt_).
.css file was also shortened a bit.

### CODE REVIEW

**Review by sbeaver-netgate — CHANGES_REQUESTED** [review]
Please create a Redmine issue at https://redmine.pfsense.org/projects/pfsense/issues specifying the need/benefit of this change.

Redmine issues help us to track, test and document changes to the codebase.

Thanks.

**Comment by GChuf** [comment]
@sbeaver-netgate done!
https://redmine.pfsense.org/projects/pfsense/issues?page=46

**Comment by sbeaver-netgate** [comment]
Thanks

Setting status to testing required

**Comment by sbeaver-netgate** [comment]
Needs to be tested. In particular fonts-awesome icons and their positioning, SVG images international translations

**Comment by GChuf** [comment]
I can provide screenshots from before and after the change if you can tell me which sites you'd like to see (and/or which browsers).

**Comment by vktg** [comment]
Successfully tested on 2.6.0.a.20210513.0100
Browsers:
Firefox 78.10.0esr (Linux)
Firefox 83 (Windows7)
Chromium 90.0.4430.93 (Linux)

**Pull request merged**
