### PR TITLE
fix for Bug #4238

### PR DESCRIPTION
**Pull request by xbipin**
fix for Bug #4238

### CODE REVIEW

**Comment by rbgarga** [comment]
I don't think change the behaviour is the right fix here, I'll investigate a bit

**Comment by xbipin** [comment]
actually if u look at other pages where this port selection is that code doesnt appear there thats y it works fine there and not here, i compared it with 2.1.5 files as well

**Comment by xbipin** [comment]
same page if u look at destination port field it doesnt have that code

**Comment by rbgarga** [comment]
I pushed a different fix for it, changing javascript to set width just before show the popup. Could you please test it and close this one?

**Comment by xbipin** [comment]
i tried ur fix but still broken, try on the firewall_rules_edit.php which was actually reported where the issue was

**Comment by xbipin** [comment]
to test do this, create 2 port aliases with names as a1 and a2, then goto firewall rules and add a new rule and in source port type a and ull see its still broken

**Comment by rbgarga** [comment]
I was able to reproduce and to test the fix. I added a ?rev=1 to all places that load autosuggest.js to avoid browser cache, but, just in case, can you try to clear your browser's cache and try again?

**Comment by xbipin** [comment]
ys works now

**Pull request closed without merging**
