### PR TITLE
Bug fix for #4605. After base64 encoding username/password, properly escape characters =,+,/ before submitting auth details

### PR DESCRIPTION
**Pull request by the-real-ed**
Sorry, my original pull request (https://github.com/pfsense/pfsense/pull/1711) referenced the wrong bug number.

This is attempt number two.

For details regarding the patch, please see: https://redmine.pfsense.org/issues/4605#note-1

### CODE REVIEW

**Comment by ermal** [comment]
Can you please sign CLA as described at https://www.pfsense.org/about-pfsense/#legal

**Comment by the-real-ed** [comment]
Done.

**Comment by rbgarga** [comment]
I couldn't find your CLA, what is your name?

**Comment by the-real-ed** [comment]
My name: Edin Sarajlic
My username for pfsense Portal: edinsarajlic

**Comment by rbgarga** [comment]
Thanks

**Comment by rbgarga** [comment]
Manually merged, thanks!

**Pull request closed without merging**
