### PR TITLE
Allow packages to request syslogd log socket to be created inside chroot

### PR DESCRIPTION
**Pull request by k-paulius**
by specifying it in /package/logging/logsocket element. Implements #4898.

Example:
<package>
	<logging>
		<logsocket>/var/appname/var/run/log</logsocket>
	</logging>
</package>

### CODE REVIEW

**Comment by PiBa-NL** [comment]
Can you rebase it on current master?
Id like to use this in haproxy package as well :).

**Comment by k-paulius** [comment]
I can do that, however it will be at least a week until I can get to it.

**Comment by rbgarga** [comment]
@k-paulius please do and let me know so I can review and merge it

**Comment by k-paulius** [comment]
Closing. New pull request #2616 opened.

**Pull request closed without merging**
