### PR TITLE
webgui, top menu scroll bar for many items, and absolute position for smaller screens to keep menu usable

### PR DESCRIPTION
**Pull request by PiBa-NL**
webgui, top menu scroll bar for many items, and absolute position for smaller screens to keep menu usable

- [x] Redmine Issue: https://redmine.pfsense.org/issues/8419
- [x] Ready for review

### CODE REVIEW

**Comment by PiBa-NL** [comment]
I don't have an iPhone.. but on Android with a Chrome browser and fixed top menu as it used to be that menu cannot be used as it doesn't show half of the menu options.... So that the menu is not fixed anymore is better in that case, i have intentionally broken that 'fix top menu' for such smaller screens..

The scrollbar should work for screens wider than 990px at least on a regular W10 computer.

So imho its still a improvement.?

**Comment by sbeaver-netgate** [comment]
The intention was that the user select "Scroll with screen" on small screens, "Fixed" on large screens. There are always more ways of addressing a problem though.

While this PR may, or may not be an improvement, I don't think we should render an existing control ineffective in this way. If this mode of operation is desired (and I'm not sure it is) then at least the Setup->General->web UI control needs to be changed to reflect the new operation.

I wonder if a better solution would be to have the control automatically force "scroll with screen" mode on small screens?

The scroll bar you added does not seem to work on iOS devices.

**Comment by PiBa-NL** [comment]
Okay, i can remove the "@media (max-width: 991px) {" part as that changes settings 'undesirably'. (I do wonder how you intend to use the menu though if you cant reach some of the buttons.. Or change the setting each time when sitting behind a different device?)

Would the part for "@media (min-width:991px){" part either improve or leave behavior the same for the other devices? Not sure if youve seen the expected effect.?: https://snag.gy/AuYMxm.jpg  also make sure to hard-refresh the browser cache..

**Comment by sbeaver-netgate** [comment]
I have seen that effect, but it does not appear to work on iOS devices. Of course I have been careful to clear the cache and/or use a private browser window in each case.

**Comment by PiBa-NL** [comment]
Ok, so no 'improvement' there.. is it the same or worse as before.?

i.e. Would the >990 part be 'merge-able' ? If so i can change the commit for that. Or should i make a 3rd choice for the user to pick this specific new behavior.?

**Comment by sbeaver-netgate** [comment]
I have just spoken to some others (with more web UI experience than me) and the consensus seems to be that if we want to retain the two menu display options, the best approach is to change the control so that it becomes a "Fixed top menu on large screens" checkbox. If the user is on a tablet or phone, it should automatically switch to "scrolls with page".

On the other hand, it was suggested that perhaps the "fixed" option is of no real use and we should just do away with it.

**Comment by sbeaver-netgate** [comment]
Closing this PR for now. Wile it offers an improvement in some areas, in others it adds confusion. We may also ditch the "fixed to top of page" option before long.

**Pull request closed without merging**
