### PR TITLE
Pib

### PR DESCRIPTION
**Pull request by phil-davis**

### CODE REVIEW

**Comment by sbeaver-netgate** [comment]
Good heavens Phil, that's quick work!
Checking it over now :)

**Comment by phil-davis** [comment]
It wasn't difficult in the end - mostly a lot of changing print_info_box_np to print_apply_box without having to touch the parameter.

**Comment by phil-davis** [comment]
I see you have merged this in some sort of way - it appears in master now. I just added that extra commit above to fix the vpn_ipsec_mobile create phase1 print_info_box_np() call.
It was broken by my change to print_info_box_np() because there used to be a test for the string "create" - that test is no longer there.
Maybe you can merge that commit also, or just make the small change yourself on master.

**Comment by phil-davis** [comment]
This has already been committed - closing.

**Pull request closed without merging**
