### PR TITLE
pkg, fix, reinstall missing package

### PR DESCRIPTION
**Pull request by PiBa-NL**
change the reference from install_package(.) as this function does not exist.

https://redmine.pfsense.org/issues/8183

### CODE REVIEW

**Comment by PiBa-NL** [comment]
fixes: https://forum.pfsense.org/index.php?topic=139390.msg761926#msg761926

**Comment by NewEraCracker** [comment]
As far as I know this also needs to be backported to RELENG_2_3 (and other branches)

**Comment by jim-p** [comment]
In an effort to improve the tracking of changes and bug/feature requests, we have decided to require an entry on the [pfSense Redmine issue tracker](https://redmine.pfsense.org) associated with every pull request, and likewise the Redmine entry should also have a link back to the pull request.

If you could, please associate this PR to a Redmine issue either by locating an existing issue at https://redmine.pfsense.org or by creating a new issue. Add a link to the Redmine issue that points to this PR, and also add a link on the PR to the Redmine issue.

For more information, see https://doc.pfsense.org/index.php/Submitting_a_Pull_Request_via_Github

Thanks!

**Comment by NewEraCracker** [comment]
A little more background, this was the commit that removed the aforementioned function:
https://github.com/pfsense/pfsense/commit/f0dfdae69a3c950c269f058ac95bf6efee0b35bf

**Pull request merged**
