### PR TITLE
ipsec, allow configuration of multiple ike phase1 encryption ciphers

### PR DESCRIPTION
**Pull request by PiBa-NL**
ipsec, allow configuration of multiple ike phase1 encryption ciphers (algo/bits/hash/dh)

this is useful for mobile users that need to connect with different operating systems. This way there is no need to find a single commonly supported weaker cipher.

### CODE REVIEW

**Comment by rbgarga** [comment]
@PiBa-NL please rebase your fork

**Comment by PiBa-NL** [comment]
@rbgarga, ive rebased the config upgrade version numbers

**Comment by PiBa-NL** [comment]
Rebased.

**Comment by rbgarga** [comment]
@PiBa-NL can you please rebase it one more time?

**Comment by jim-p** [comment]
The IPsec portions look OK at a glance, will test it more once it gets rebased. The GUI additions will need some review from @sbeaver-netgate

**Comment by sbeaver-netgate** [comment]
I will review after the conflicts are resolved.

**Comment by PiBa-NL** [comment]
@rbgarga @jim-p @sbeaver-netgate , Rebased it, lemme know if something needs changing/fixing.

**Comment by sbeaver-netgate** [comment]
Clicked the "Add" button twice and added two new algorithm sections, but I could then only delete the second added section. The first added agm displays a delete button, but it doesn't do anything.

**Comment by PiBa-NL** [comment]
@sbeaver-netgate there should always be at least 1 algorithm section, so probably the delete button should get 'hidden' once there is only 1 left i havnt implemented that yet.. But it is imho a small visual detail that can be fixed later assuming the pull-request is 'technically approved' so to say.?

**Comment by sbeaver-netgate** [comment]
I had two selections on screen, and could not delete the seconds one.

**Comment by PiBa-NL** [comment]
hmm i cant seem to reproduce that..

**Comment by jim-p** [comment]
It seems to pass some basic tests here. I was able to add multiple P1 encryption sets to a tunnel. They show in the summary view, they are in the config. Clients could still connect (Win 10 and OS X). Editing the tunnel I could remove any entry I tried (first, last, middle). Looking good so far :+1:

**Comment by sbeaver-netgate** [comment]
Yeah - Sorry. That was my fault. There is not much visual distinction between each encryption section, and the authentication section above. - Perhaps others will make the same mistake. I'm trying to think of a way to improve that and also fix having the delete button hidden when only one is left. (Because I spent so much time on that with all the other "repeatable" blocks in pfSense.

Would this display be an easier way to do it? (The diff is agains current master, not your version)
pfsense_localdomain_-_vpn__ipsec__tunnels__edit_phase_1

**Comment by PiBa-NL** [comment]
Adding a section 'title' should be easy also with the current list implementation. But i must agree that your mock-up looks good. Will have to look if there was some technical difficulty that prevented me from using that. One nice thing about the new 'list' component would be that it supports more control's in their original layout. The repeatable group is limited in its ability to have more controls afaik.?. but in this case 4 is enough. So i'm not sure anymore why i started implementing a complete separate solution..

Ill take a look at using that instead, will take a few days though..

**Comment by jim-p** [comment]
In an effort to improve the tracking of changes and bug/feature requests, we have decided to require an entry on the [pfSense Redmine issue tracker](https://redmine.pfsense.org) associated with every pull request, and likewise the Redmine entry should also have a link back to the pull request.

If you could, please associate this PR to a Redmine issue either by locating an existing issue at https://redmine.pfsense.org or by creating a new issue. Add a link to the Redmine issue that points to this PR, and also add a link on the PR to the Redmine issue.

For more information, see https://doc.pfsense.org/index.php/Submitting_a_Pull_Request_via_Github

Thanks!

**Comment by jim-p** [comment]
Redmine issue: https://redmine.pfsense.org/issues/8186

**Comment by PiBa-NL** [comment]
Changes implemented from the sample code (the usable parts).

If you thinks that is not the case, can you point me to what i missed?

**Comment by sbeaver-netgate** [comment]
Looks very nice. Thank you. Sorry for the confusion, but for some reason you update was given a date from April so we did not realize it was new :(

I needed to bump the config version umbers since another update was made prior to this one. It is now 17.5 - I renamed the update function accordingly.

**Comment by PiBa-NL** [comment]
Okay i understand, thanks :)

**Pull request merged**
