### PR TITLE
dhcpd ipv4 - fix gui config to accept multiple subnets and/or answer requests from relay servers

### PR DESCRIPTION
**Pull request by marcelloc**

### CODE REVIEW

**Comment by marcelloc** [comment]
Can it be reviewed until merge conflicts issues. It's the third time I rewrite this.

**Comment by rbgarga** [comment]
Leave it as is for now, I'm going to review it and let you know. After it's reviewed you rebase your fork and we get it merged.

**Comment by nikor30** [comment]
Hi, we tryed your files today. 
But the dhcpd.conf which was created did not load. 
All networks are as pools under one subnet, in the old version you crate a subnet per pool. 
Maybe you can take a look. 
Regard niko

**Comment by nikor30** [comment]
rbgarga, how about to bring this pull request into the master ?

**Comment by zbzoch** [comment]
Any progress on this issue?

**Comment by pedymaster** [comment]
Hey, how does it look? Don't tell me, the finished work will go to waste

**Comment by rbgarga** [comment]
After discuss privately with @marcelloc he agreed to submit a fresh patch, tested on 2.3, and I'll review it as soon as it lands here

**Comment by andrewkrug** [comment]
Was this feature ever merged?

**Comment by ross-w** [comment]
We're in a position where we are trying to configure DHCP as described above, and we were slightly surprised that it is not presently possible! Can someone post a link to the fresh PR where we can track the status?

**Comment by jerrylindahl** [comment]
Found myself needing this yesterday, I assume it is still not supported? Found a dirty workaround in the meantime (I haven't tested it yet) https://happy-coder.com/2014/06/27/pfsense-custom-dhcpd-configuration/

**Comment by vc** [comment]
Any progress on this feature?

**Comment by koenr** [comment]
I need this too. Thank you for the happy coder workaround, but it's going to be very careful upgrading :-(

**Comment by ssiemens-hm** [comment]
Need this too. Would be greate to see this feature in the near future.

**Comment by nveeser** [comment]
+1 for using this

**Comment by toboshii** [comment]
+1 for this basic functionality...

**Comment by jzapater** [comment]
+1 also

**Comment by tofazzz** [comment]
+1 what happened to this request?

**Comment by Akshay-Hegde** [comment]
+1  official merge would be very much helpful it can really simplify messy setup example in my case, I have more than 25 vlans, creating 25+ vlan interfaces on pfsense and enabling DHCP on each interface is really tedious job practically, what if there are many more vlans.

From last few years I have been waiting for this feature as everything is relayed through  switch as a DHCP relay to single DHCP server in my case.

The day it gets merged I will migrate from ISC DHCP to pfsense.

Any updates on feature implementation ?

**Pull request closed without merging**
