### PR TITLE
Internationalize Form_Button text

### PR DESCRIPTION
**Pull request by phil-davis**
The text of a Form_Button is not translated internally. Some Form_Button
calls already had the button text enclosed in gettext(), this does it
for the remaining ones.
So now all buttons have the chance to have a translation.

### CODE REVIEW

**Comment by jim-p** [comment]
@phil-davis Looks like somehow this already has conflicts, can you check it and rebase?

**Comment by phil-davis** [comment]
Yes, I had started in a branch from a couple of hours ago. Should be good now.

**Comment by rbgarga** [comment]
If Form_Button 2nd parameter must be considered on gettext, it would be easier to add this to tools/scripts/update_pot.sh as it was done for other functions. Then we don't need to remember to add explicit calls on this specific function

**Comment by phil-davis** [comment]
It would need both:
1) A gettext() to actually be done somewhere inside Form_Button so that the underlying code actually translates the parameter.
2) Enhance update_pot.sh to gather the strings in the parameter as @rbgarga mentions.

Is that the way you want to go?

**Comment by phil-davis** [comment]
In update_pot.sh there is already:
```
-kForm_Button:2
```
So the strings should be being collected for translation.
I guess the missing thing is inside Form_Button - it does not actually attempt translation anywhere in the code.

**Comment by phil-davis** [comment]
Maybe it is this easy: https://github.com/pfsense/pfsense/pull/2736

**Comment by phil-davis** [comment]
This won't have done harm in normal operation, but actually should have been unnecessary since #2736 does the translation inside Form_Button.
It does result in gettext() being called twice on the string. That is a little bit of wasted performance, and for unusual cases can mean the translation ends up wrong if the first translated word happens to translate to a word that is also a translatable word in the original language.
e.g. Let's imagine that in some language en_US "Filter'" -> zz_XY "Fritter"
Then we send "Fritter" through gettext(). If en_US "Fritter" appeared somewhere else in the UI, then it will have a translation, and so now the translation of en_US "Fritter" will get displayed when we really want just the translation of en_US "Filter".
Anyway, in reality that rarely (or never) happens.

**Comment by rbgarga** [comment]
I've reverted this

**Pull request merged**
