### PR TITLE
Fix #7317 Widget Filter All button

### PR DESCRIPTION
**Pull request by phil-davis**
Make the "All" button less enthusiastic about checking checkboxes. It should only check the selections related to its own widget.

### CODE REVIEW

**Comment by phil-davis** [comment]
Note: This should cherry-pick back to RELENG_2_3 fine, because all the widget filtering stuff has been back-ported there.
If it is cherry-picked back to RELENG_2_3_3 then either:
1) First also cherry-pick the System Information Widget filtering change (which only so far got back as far as RELENG_2_3)
or
2) Do not apply the System Information Widget change back into RELENG_2_3_3

**Comment by phil-davis** [comment]
@sbeaver-netgate And another little fix that is going to make merge conflicts. The sooner it is merge the sooner the pain is over.

**Comment by sbeaver-netgate** [comment]
done

Steve

**Comment by phil-davis** [comment]
@sbeaver-netgate the commit for this has not come yet?

**Pull request merged**
