### PR TITLE
Update dyndns.class

### PR DESCRIPTION
**Pull request by johnbyronent**
Fix Certificate validation issue

### CODE REVIEW

**Comment by cbuechler** [comment]
I'd really rather not disable cert validation, especially since if they fix their F graded HTTPS config it would work as is. 
https://www.ssllabs.com/ssltest/analyze.html?d=update.eurodyndns.org

They're missing part of the cert chain. Chrome figures it out, which is why I didn't notice when I enabled cert verification there. curl, fetch, wget and similar tools fail because of the incomplete chain. 

I'm guessing you must be a customer of theirs, could you instead open a support request with them requesting they fix their HTTPS setup?

**Comment by johnbyronent** [comment]
I will try to see if I can have them fix it.
But indeed I don't have any control on it.

**Comment by Gertjanpfsense** [comment]
johnbyronent   :: "But indeed I don't have any control on it."
I guess that mentioning this test : https://www.ssllabs.com/ssltest/analyze.html?d=update.eurodyndns.org&latest will motivate them.
It will take them a couple of minutes to get their certificate straight.

**Comment by rbgarga** [comment]
Disable cert validation is not the way to go here.

**Pull request closed without merging**
