### PR TITLE
Add OnAppV4 record update as Dynamic DNS Client

### PR DESCRIPTION
**Pull request by TroyDesign**
https://docs.onapp.com/display/40API/Edit+DNS+Records

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by TroyDesign** [comment]
Sorry, I have just done it.

**Comment by rbgarga** [comment]
Please add OnApp item to header at:
https://github.com/pfsense/pfsense/blob/master/src/etc/inc/dyndns.class#L59

**Comment by TroyDesign** [comment]
Did it, thank you

**Comment by rbgarga** [comment]
@TroyDesign can you please rebase your fork? It cannot be automatically merged anymore

**Comment by sbeaver-netgate** [comment]
No response to rebase request in six months

**Pull request closed without merging**
