### PR TITLE
bootstrap usr/local/www a to e minor edits

### PR DESCRIPTION
**Pull request by phil-davis**

### CODE REVIEW

**Comment by jim-p** [comment]
This one wouldn't merge cleanly -- may need to wait for the git sync of the others being merged to catch up and then rebase/resubmit

**Comment by phil-davis** [comment]
Hmmm - I merged conflicts not long ago. I will look and merge again.

**Comment by phil-davis** [comment]
This should commit OK now.

**Comment by phil-davis** [comment]
And merged again.

**Comment by phil-davis** [comment]
@jimp I keep merging to bootstrap. If someone can commit this it will save re-merging it every few hours.

**Comment by jim-p** [comment]
Yeah sorry, got sidetracked by lots of other things yesterday. It's coming in right now, thanks!

**Pull request merged**
