### PR TITLE
implement rule hit count/show/kill

### PR DESCRIPTION
**Pull request by marcelloc**

### CODE REVIEW

**Comment by marcelloc** [comment]
rule_count
rules_count_kill_states_3
rules_count_show_states

**Comment by LinuxTracker** [comment]
It's a stunningly beautiful display of useful data.

A++++++++++++ Strongly encourage integration!

**Comment by rbgarga** [comment]
@marcelloc, all interface is being converted to bootstrap on bootstrap branch. Adding a GUI change on branch master at this point would create conflicts for future merges. What do you think about implementing this on branch bootstrap?
It would make things easier, right @sbeaver-netgate?

**Comment by sbeaver-netgate** [comment]
Yes it would. Shouldn’t be that big a deal on the Bootstrap branch.

Steve
--
Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com | www.netgate.com

**Comment by marcelloc** [comment]
I've never used bootstrap. I'll try to sync with Bootstrap branch but if you can help on this, would be great.

**Comment by rbgarga** [comment]
@marcelloc, if you have questions, you can ask @sbeaver-netgate

**Comment by rbgarga** [comment]
@marcelloc, if you have questions, you can ask @sbeaver-netgate

**Comment by rbgarga** [comment]
@marcelloc bootstrap branch is gone, it was integrated into master. Now you need just to adapt the code to work on the new world

**Pull request closed without merging**
