### PR TITLE
Add support for DHCP when interface is set to track a delegated prefix (#1638 for 2.2)

### PR DESCRIPTION
**Pull request by WilliamHiles**
This is a Robert Nelsons pull (pull #1638) for 2.2.  

No changes.  Just submitted for easy integration with the 2.2 branch.

### CODE REVIEW

**Comment by rbgarga** [comment]
This is a big change and cannot be integrated to 2.2.x at this point because it's a maintenance branch.

I'm finishing to import DDNS related changes to master branch, after that, if you want to submit the dhcpd for track interfaces part to master branch it would be nice.

**Comment by WilliamHiles** [comment]
Thanks for the quick response.  In some forum posts there are suggestions that somebody from the core team might be working on this for 2.3.  Do you know if that is happening?

**Comment by rbgarga** [comment]
@WilliamHiles ouch, nevermind, I'm working on it for 2.3

**Comment by rbgarga** [comment]
You can follow progress on https://redmine.pfsense.org/issues/3029

**Pull request closed without merging**
