### PR TITLE
Feature 10374

### PR DESCRIPTION
**Pull request by Wasurerarenai**
- [x] Redmine Issue: https://redmine.pfsense.org/issues/10374
- [x] Ready for review

### CODE REVIEW

**Comment by Wasurerarenai** [comment]
I tested the PR with the "System Patches" package details from https://docs.netgate.com/pfsense/en/latest/development/system-patches.html. The patch tested and applied successfully. The needed ARM 32 & 64 fields properly populated the services_dhcp.php page on my pfSense system running REL 2.4.4. Along with the TFTPD package installed and configured I was successfully able to boot Raspberry Pi 3B devices with https://github.com/ipxe/pipxe pulling "bootaa64.efi" from the pfSense system.

**Comment by rbgarga** [comment]
@Wasurerarenai we do not apply changes direct to stable versions.  Please re-submit it against `master` branch instead of `RELENG_2_4_4`

**Comment by Wasurerarenai** [comment]
Got it, will resubmit.

**Comment by Wasurerarenai** [comment]
Resubmitted PR as #4279. Closing this one.

**Pull request closed without merging**
