### PR TITLE
Changed the file - load_balancer_virtual_server.php, for Bootstrap UI

### PR DESCRIPTION
**Pull request by itshari**

### CODE REVIEW

**Comment by itshari** [comment]
Any reasons for closing this request? Am I missing something?

**Comment by jim-p** [comment]
I thought it was part of a different submission related to the other pull request you had put in. This whole area is slated for a review/rewrite by our internal developer(s) working on bootstrap already. I'll open it back up and see if it's something they want to take now or wait.

**Comment by jim-p** [comment]
It also has merge conflicts that need to be fixed, so you'll need to rebase the fork and fix any other issues.

**Comment by itshari** [comment]
I've removed the conflict and given a new pull request.

**Pull request closed without merging**
