### PR TITLE
Fix invalid regular expression error on Chrome Beta channel

### PR DESCRIPTION
**Pull request by NewEraCracker**
https://forum.pfsense.org/index.php?topic=117007.msg650206

### CODE REVIEW

**Comment by NOYB** [comment]
Why does Chrome think escaping characters in a regular expression is invalid?  It should be perfectly legit.  If Chrome does not accept that then I think it's Chrome that is broken.

**Comment by rbgarga** [comment]
This change is wrong. If you don't escape '.' on a regular expression it means 'any character' so it will never fail

**Comment by NOYB** [comment]
That was one of my thoughts too but didn’t point it out because not sure if ‘.’ is ‘any character’ when part of a range, and too lazy to look it up.  If I recall some special meanings are a little different inside of a range.  But rather than committing them all to memory I like to just escape them all and be done with it.

**Comment by NewEraCracker** [comment]
> This change is wrong. If you don't escape '.' on a regular expression it means 'any character' so it will never fail

> That was one of my thoughts too but didn’t point it out because not sure if ‘.’ is ‘any character’ when part of a range, and too lazy to look it up.

Checking the expression online gives:
```
    [a-zA-Z0-9_.:]+ match a single character present in the list below
        Quantifier: + Between one and unlimited times, as many times as possible, giving back as needed [greedy]
        a-z a single character in the range between a and z (case sensitive)
        A-Z a single character in the range between A and Z (case sensitive)
        0-9 a single character in the range between 0 and 9
        _.: a single character in the list _.: literally
```
Source: https://regex101.com/

**Comment by NOYB** [comment]
The existing escaped expression is valid.  Anything that doesn’t deal with it is what is broken and should be fixed.  Including Chrome.  Especially if it is beta version.

`
[a-zA-Z0-9\_\.\:]+ match a single character present in the list below
Quantifier: + Between one and unlimited times, as many times as possible, giving back as needed [greedy]
    a-z a single character in the range between a and z (case sensitive)
    A-Z a single character in the range between A and Z (case sensitive)
    0-9 a single character in the range between 0 and 9
    \_ matches the character _ literally
    \. matches the character . literally
    \: matches the character : literally
`

**Comment by NewEraCracker** [comment]
This bug has made its way into Google Chrome 53 Stable (53.0.2785.89)
This workaround is the only way to make pages work.

**Comment by NOYB** [comment]
"This workaround is the only way to make pages work."
There are other ways to make the pages work.  Use a browser that adheres to the regex expression spec.

**Comment by NewEraCracker** [comment]
Closing this in favor of #3127 which contains further fixes for same issue in other areas.

**Pull request closed without merging**
