### PR TITLE
Add mising gettext() calls

### PR DESCRIPTION
**Pull request by phil-davis**
As reported in forum https://forum.pfsense.org/index.php?topic=124734.msg689931#msg689931 , sprintf() inside a setHelp() method call means that the text string is not picked up in the ".pot" file for translation. In some places these already have an explicit gettext() put around them. These are the remaining places with a setHelp(sprintf()) sequence that need a gettext() added.

### CODE REVIEW

**Comment by rbgarga** [comment]
What about if we change SetHelp() and other methods that contain strings to be translated to work with multiple parameters and do sprintf and gettext internally?

What do you think @sbeaver-netgate and @phil-davis ?

**Comment by rbgarga** [comment]
Then we would be able to call
```
->SetHelp("This is %s string", "foo");
```

**Comment by sbeaver-netgate** [comment]
Good idea.

**Comment by phil-davis** [comment]
Sounds good, if it can be implemented fairly quickly so that the enthusiastic translators get the strings soon.

**Comment by sbeaver-netgate** [comment]
I will try to get to it today

**Comment by rbgarga** [comment]
Cool @sbeaver-netgate, you can check at https://github.com/pfsense/pfsense/blob/master/tools/scripts/update_pot.sh#L53 all methods we are collecting strings to create pot

**Comment by sbeaver-netgate** [comment]
The setHelp method already accommodates this, albeit in a slightly unconventional way. setHelp accepts a second argument, which is an array of args that are passed to sprintf. The first argument does get the gettext treatment. e.g.:
`$section->addInput(new Form_Input(
	'descr',
	'Description',
	'text',
	$pconfig['descr']
))->setHelp('A description may be entered here for %d administrative reference %s (not parsed).', array(23, "fish"));`

Produces:
 A description may be entered here for 23 administrative reference fish (not parsed).

So we can either keep it as it is, or I could revise it to use a more conventioanl format, as in:
`->sethelp("Do this %d times, and do it %s", 4, "slowly");`

**Comment by sbeaver-netgate** [comment]
The setHelp() methods have been updated to no longer require the use of sprintf, and to apply gettext() to the first argument.

**Pull request closed without merging**
