### PR TITLE
Suggested format changes to copyright

### PR DESCRIPTION
**Pull request by phil-davis**
Those spaces in the lines of section 4 are still being pasted in.
I suggest closing the double-quotes of the acknowledgment text.
Of course every copyright section has variations on the formatting. It still needs someone to declare a final correct version, and then someone to paste it everywhere.

### CODE REVIEW

**Comment by doktornotor** [comment]
WTH is with indentation there? Noone writes paragraphs like this, completely backwards- if anything, should be the first list that has the extra tab, if anything.

**Comment by phil-davis** [comment]
I am surprised, but actually I do not care any more. If everyone is going to paste in a differently formatted copyright section every day, then so be it. I just have to get some therapy for my OCD tendencies :)

**Comment by doktornotor** [comment]
I probably have some OCD as well.... Or, it's just that the header is the thing that immediately strikes you since it's the very first thing you see in the file. This looks like it was "formatted" by someone who keeps using space key instead of styles in MS Word. (Also, the ShrewSoft copyright line in this one file, god knows where this got pasted from from.)

**Comment by jlduran** [comment]
That's the purpose of adding an [`.editorconfig`](http://editorconfig.org) file to the project. Apparently some developers are not taking advantage of it.

**Comment by phil-davis** [comment]
Closing since this is a general issue in all files for ESF to sort out. Nothing to be gained by having this particular example sitting in the open pull requests list. The matter has been brought to people's attention.

**Pull request closed without merging**
