### PR TITLE
Feature #2869 LDAP group membership improvements

### PR DESCRIPTION
**Pull request by BrettMerrick**
Added a "~~Directory Type~~ Group Membership Location" drop down to the User Manager => LDAP Server configuration that provides "~~AD~~ User Attribute" and "~~rfc2307bis~~ Group Attribute" options.
* "User Attribute" maintains the current functionality; looks for membership attributes in the user object.
* "Group Attribute" looks for group objects where the user is in a member attribute.

TODO:
* ~~Replace the gui config options with something more accurate and descriptive....~~
* Support configurations where the member attribute contains the dn of the member rather than the username represented as uid, cn or similar.
* Support for nested groups.

### CODE REVIEW

**Comment by rbgarga** [comment]
Please respect Developer style guide - https://doc.pfsense.org/index.php/Developer_Style_Guide

**Comment by BrettMerrick** [comment]
I've had a look at the link supplied, however, since I'm a new contributor to this project could you help me to get my contribution ready for inclusion and point me to the specific guideline I've neglected to observe?

**Comment by BrettMerrick** [comment]
* Code reviewed against Developer style guide.
* If new config option is missing then it now correctly defaults to original behaviour.
* Gui terminology improved to reflect function:
screen shot 2015-07-08 at 12 10 30 pm

**Comment by BrettMerrick** [comment]
Feature #809 (New): Config sync username change - removed the username option from the sync configuration to prevent confusion as discussed in issue tracker.

**Comment by sbeaver-netgate** [comment]
Please resubmit for consideration in 2.3.1

**Pull request closed without merging**
