### PR TITLE
interfaces.php Custom reset text typo

### PR DESCRIPTION
**Pull request by phil-davis**

### CODE REVIEW

**Comment by phil-davis** [comment]
@sbeaver-netgate please look and commit if you like, before your next round of edits makes conflicts.

**Comment by sbeaver-netgate** [comment]
No changes will be accepted to this file while it is a WIP. Once I have finished and tested the conversion I will mark the file as complete and will then accept comments/updates.

**Comment by phil-davis** [comment]
Well can you then please make these typo corrections to the version you are editing, because it seems pointless for you to be editing and testing without including fixes for observed bugs and text typos.
I don't care how the changes get in, but I might as well report them when I notice them - I am not testing, just reading the code.

**Comment by phil-davis** [comment]
I can easily observe the commits that you make, and then close these pull requests as I see that each little 1-line fix has been made.

**Comment by sbeaver-netgate** [comment]
Thank you Phil, I would be glad to. Our current set-up makes PRs a little difficult to handle. Forks of forks or branches of versions of goodness knows what.

I would be very pleased to receive your comments and to incorporate them as I edit. Much easier for me that way, at least until Bootstrap is merged into the main product repo.

The interfaces.php page is a monster. I have just completed the first pass (convert HTML to PHP framework) but have not even checked that for typos, element names, values yet. I am so swamped with bug fixes. Many of the pages that were reported as converted can not have been tested and are horribly broken. I see you looked at carp_status.php this evening. Case in point. What a total mess.

Thanks again for your input. It really helps. Feel free to email directly if you wish. sbeaver@netgate.com

**Comment by phil-davis** [comment]
Yes, I was just scrolling through the code to pick out any obvious bugs and make sure that fixes from "recent" times from the RELENG_2_2 and master branches have actually integrated into bootstrap OK. I mainly want to help avoid any regressions!

**Comment by doktornotor** [comment]
Regarding regressions:

@sbeaver-netgate Why's the "Copy my MAC" thing back YET again?

https://redmine.pfsense.org/issues/5040

**Comment by phil-davis** [comment]
Hey - don't highjack my thread :)

**Comment by jim-p** [comment]
@sbeaver-netgate incorporated the changes manually.

**Pull request closed without merging**
