### PR TITLE
Allow URLs for TFTP Server (Bug #6634)

### PR DESCRIPTION
**Pull request by doktornotor**
The setPattern() thing ain't usable for this and just causes regressions; also is_URL() from util.inc is way too limited for this purpose.

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by doktornotor** [comment]
Guys, you've got some issues with your CLA script (already done), plus I do not think this damned paperwork is useful any more after relicensing the whole thing to Apache license.

**Comment by jim-p** [comment]
The original CLA signing was set to expire in a year, new one won't expire, you do need to sign it again though, but just one last time.

**Comment by ravenblue12** [comment]
I tested it and it works!

**Pull request merged**
