### PR TITLE
Handle single quotes in user names for CP

### PR DESCRIPTION
**Pull request by phil-davis**
Forum: https://forum.pfsense.org/index.php?topic=110243.0
This is a trial - make sure it really works before committing.

### CODE REVIEW

**Comment by heper** [comment]
@phil-davis i can confirm your fix works for my AD testuser: test'abcd
thanks a lot

**Comment by phil-davis** [comment]
I noticed that there is code that does stuff like:
			$safe_username = SQLite3::escapeString($username);
Maybe this escapeString() call is the more correct generic way to make sure that odd characters in strings are appropriately escaped for use in SQL.

**Comment by phil-davis** [comment]
See https://github.com/pfsense/pfsense/pull/2887 for alternate solution that should be better, assuming it owrks.

**Comment by phil-davis** [comment]
Closing in favor of #2887

**Pull request closed without merging**
