### PR TITLE
dhcp_lease_counter

### PR DESCRIPTION
**Pull request by heper**
lease_counter
shows # of leases in use, for each pool

### CODE REVIEW

**Comment by heper** [comment]
https://redmine.pfsense.org/issues/5186

**Comment by rbgarga** [comment]
Hello @heper. In order to get patches accepted you must sign a CLA as described at https://www.pfsense.org/about-pfsense/#legal

**Comment by rbgarga** [comment]
Other than that, RELENG_2_2 is a maintenance branch, can you please submit a new PR against branch master?

**Comment by heper** [comment]
i signed the CLA.
i guess i could try to figure out how it works in the master branch, but i'd have no way to test it. (as i don't know how i would get the new bootstrap/master thing running)

**Comment by rbgarga** [comment]
Closed in favor of #1932, lets preserve RELENG_2_2 without such changes. Thanks!

**Pull request closed without merging**
