### PR TITLE
proposed fix #6175

### PR DESCRIPTION
**Pull request by heper**
needs careful review, to be sure this doesn't cause other issues

### CODE REVIEW

**Comment by sbeaver-netgate** [comment]
Change suggested by Jorge M. Oliveira was found to be effective and has been merged.
Thanks Heper and Jorge. 

Since this issue is difficult to reproduce, please confirm that the fix was effective.

**Comment by heper** [comment]
@sbeaver-netgate can't seem to find the commit / problem remains after gitsync releng_2_3
did you forget to push it online ?

**Comment by sbeaver-netgate** [comment]
I'll check

**Comment by NewEraCracker** [comment]
Indeed. At time of this comment writing. Change isn't show here:

https://github.com/pfsense/pfsense/commits/master/src/usr/local/www/firewall_aliases_edit.php
https://github.com/pfsense/pfsense/commits/RELENG_2_3/src/usr/local/www/firewall_aliases_edit.php

**Pull request closed without merging**
