### PR TITLE
System Update Settings - GitSync Options

### PR DESCRIPTION
**Pull request by NOYB**
Add GitSync options selectors to post update GitSync.
Minimal, Diff, Verbose, Dry Run

The GitSync options have utility for post update sync also.

Also applicable to RELENG_2_3_2.

Dependency Note:
The verbose option will need to be split out into "show_files" and "show_command" when the following commit is applied.
https://github.com/pfsense/pfsense/pull/3168/commits/a6fd4c0ff4141a1836ed74add1df55477d87ddd0

### CODE REVIEW

**Comment by rbgarga** [comment]
What would be the idea of having options like --dry-run or --show-command set on GUI?

**Comment by NOYB** [comment]
Testing, debugging, troubleshooting, etc.  Same reasons one might use them in the command shell.

**Comment by rbgarga** [comment]
@NOYB can you please re-submit it for master branch?

**Comment by NOYB** [comment]
For master branch
https://github.com/pfsense/pfsense/pull/3436

**Pull request merged**
