### PR TITLE
Add options to build zabbix3 packages

### PR DESCRIPTION
**Pull request by dbaio**
Preparing for packages upgrade

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by dbaio** [comment]
I did last year. 
Is necessary do it again ?

**Comment by cbuechler** [comment]
@dbaio they were originally only valid for a year, now are indefinitely. Yes if you can please do it once more then it'll be good.

**Comment by dbaio** [comment]
ok, done.

**Pull request merged**
