### PR TITLE
Redmine #4568 Preserve MLPPP settings when saving interface settings

### PR DESCRIPTION
**Pull request by phil-davis**
The interface.php UI only displays and allows the user to edit the first
(0) element of the "localip" "subnet" and "gateway". I changed the name
of some POST fields so that it is clearer that they just contain the "0"
element of the list.
If there are other elements (i.e. if there is MLPPP happening) then
these are preserved across save, even though they are not displayed to
the user for editing. The "Advanced" message gets the extra text "There
are additional Local and Remote IP addresses defined for MLPPP."
displayed so the user can know that there is more data and where to
click to see and edit it.
IMHO this is a reasonable way to fix this bug. There does not seem much
to be gained by putting a whole lot of code here to edit a variable
number of Local-Remote IP Address sets when that is already easily
available in interfaces_ppps_edit.
This is a resubmit of #1822 after integrating to the current master.

Note also: https://github.com/pfsense/pfsense/pull/1899 makes small fixes to the code that are also used here. There might be merge conflicts with that that I will have to resolve after it is committed.

### CODE REVIEW

**Comment by phil-davis** [comment]
OK - I am now officially tired of constant merging of this stuff. Overnight, interfaces.php changed completely to being indented with space rather than tabs. I have merged this PR once again and made the format of my added lines match the new format of interfaces.php
The PR for this fix has been available for a long time. If you care at all about community contributions then take them and merge them. Supposedly this is an open-source project that in theory wants to encourage community contribution. Lately is has become clear that it is actually a company project that is open-source. Community contributions are just left sitting.
Sorry for the rant, but I am sick of merging conflicts every day.

**Comment by doktornotor** [comment]
@sbeaver-netgate - Could you fix your editor settings? This indentation regressions and stupid spaces officially suck. Stop breaking other people's work. You have fscked-up the indenting in the entire file.

**Comment by sbeaver-netgate** [comment]
My apologies. I very much understand your (and Phil Davis') concern.  Those changes were accidental and I don’t really know how they occurred. I typically edit a file, test it, then check it for style and check the copyright. I use git diff -w as a final check.

Did I accidentally invoke the editor’s “Convert tabs to spaces” command? I just don’t know, but I will certainly revert and fix that.

I will start to check my work without the ‘-w’ in the diff to make sure there are no more spacing changes.

Again, my apologies for breaking this. It was not my intention of course and is in no way an indication of my respect for everyone’s contributions to the project which I so deeply appreciate.

Steve
--
Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com | www.netgate.com

**Comment by rbgarga** [comment]
@phil-davis you don't need to re-do the merge here, @sbeaver-netgate will check the changes and let you know if they are OK

**Comment by doktornotor** [comment]
:laughing: :grinning:

**Comment by phil-davis** [comment]
I re-did the changes again anyway. Hopefully the last time.
Closed in favor of https://github.com/pfsense/pfsense/pull/1900

**Pull request closed without merging**
