### PR TITLE
Allow "From" field in RFC822 format

### PR DESCRIPTION
**Pull request by thiagoc**
This allow notification email "From" field with a custom format rather the default e-mail address.

### CODE REVIEW

**Comment by rbgarga** [comment]
Sorry about the long delay. Can you please rebase your fork? Patch doesn't apply clean anymore

**Comment by rbgarga** [comment]
PHP also provides a function to deal with it, it would be preferred over this regex.

http://php.net/manual/pt_BR/function.mailparse-rfc822-parse-addresses.php

**Comment by thiagoc** [comment]
Hi @rbgarga, this PHP function requires the mailparse module, I'm trying to figure out how to install it. Do you think this is better than the regex solution? If so, how can I add the mailparse module?

**Comment by thiagoc** [comment]
I have simplified the code on the pull #1726, please review it.

**Pull request closed without merging**
