### PR TITLE
Diagnostics / Tables - URL Table Aliases

### PR DESCRIPTION
**Pull request by NOYB**
Handle URL table aliases similar to bogons tables.  Suppress record remove buttons.
Update (download) only the selected URL table alias instead of all of them.
Retain full line comments in downloaded URL table files so we can view and use them.
When URL table file full line comments are present, provide view option in info box.
Increase ability to extract last update date from wider variety of URL table file comments.

### CODE REVIEW

**Comment by sbeaver-netgate** [comment]
There is a small glitch in that "Hide table comments." seems to get broken into two lines?

break

**Comment by NOYB** [comment]
Hmmm.  I've never seen that.  What is your browser width there?

**Comment by sbeaver-netgate** [comment]
Very wide indeed. The issue shows up at any width.

Steve
--
Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com | www.netgate.com

**Comment by NOYB** [comment]
Only way I seem to be able to reproduce that (Chrome & IE; Win 81.Pro) is to go very narrow.  Any idea's?  Do you have a system that it doesn't occur on?  Maybe the differences between them could provide a clue.

**Comment by sbeaver-netgate** [comment]
Sorry for delay. It seems it is only an issue with fief. We could move the <br> to the beginning of the line (in front of the second “i”) or just live with it.

Steve
--
Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com | www.netgate.com

**Comment by NOYB** [comment]
Pull request submitted.
https://github.com/pfsense/pfsense/pull/2694

**Pull request merged**
