### PR TITLE
Add standard deviation to gateway status and widget

### PR DESCRIPTION
**Pull request by dennypage**

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by dennypage** [comment]
I have previously signed the CLA, and had a PR accepted a few weeks ago. Is there a new version?

**Comment by sbeaver-netgate** [comment]
CLAs have been a little unreliable recently. Someone will fix this manually.

**Comment by rbgarga** [comment]
I couldn't find the CLA, maybe it was signed in the past and expired after 1 year. Nowadays it doesn't expire anymore. @jdillard can you take a look to make sure if CLA is signed or not?

**Comment by jdillard** [comment]
@dennypage It looks like your old CLA expired on 1/5/2016. As @rbgarga mentioned the CLAs no longer automatically expire, so if you could log in and fill it out again (most of your info is saved) that would be appreciated: https://portal.pfsense.org/members/signup/ICLA

The automated system will pick it up shortly after that and autocorrect any PRs.

**Comment by dennypage** [comment]
Thanks for checking Jared. Missed it by two weeks. :) I'll try to sign a new one tonight.

**Comment by jdillard** [comment]
No worries. It should be smooth sailing from then on, but if you have problems feel free to ping me.

Thanks for all of your contributions!

**Comment by dennypage** [comment]
Actually it looks like it worked doing it from my phone. Awesome. Please let me know if there is any issue. Thanks.

**Comment by cbuechler** [comment]
Thanks @dennypage !

**Pull request merged**
