### PR TITLE
Support for special cases of TLD for specific countrys, like Brazil.

### PR DESCRIPTION
**Pull request by ancientz**
Small code change to support TLDs from Brazil which have two levels, like .com.br, and in the current code does not work. It should work for countries with even more levels, but haven't tried it.

Didn't have time to make some better working code, but It works and suit me immediate need, if anyone want to make a better code, be my guest :)

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by rbgarga** [comment]
@ancientz could you please sign the CLA as described at https://www.pfsense.org/about-pfsense/#cla ? Without it this patch cannot be reviewed / merged

**Comment by ancientz** [comment]
@rbgarga Hi, sorry it took too long, just did the online CCLA form.

**Comment by rbgarga** [comment]
The idea is good, but I believe there should be a better way to implement it including all other TLDs supported by IANA. Adding just com.br and net.br hard coded is not the way to go IMO

**Comment by jim-p** [comment]
Trying to detect/parse out the hostname and TLD or subdomain parts is too error prone for country-specific TLDs and subdomains. The Namecheap code path already has code for separate domain and hostname fields. If another DynDNS provider needs them separated and has similar parsing issues, it should be converted to that style instead.

**Comment by ancientz** [comment]
@rbgarga I agree, but I could not think of a simpler way to do this, considering that there might be (I'm not sure) other countries with TLDs based with two subdomains, something like .net.sc.br, and so on. I think @jim-p alternative is the best, that way solve all the problems and also make the code cleaner than It is right now.

**Comment by rbgarga** [comment]
Agreed, so I'm closing this one and we can have specific PRs as needed. Thanks!

**Pull request closed without merging**
