### PR TITLE
Some small interface improvements + tweaks

### PR DESCRIPTION
**Pull request by luckman212**
- interfaces => add "copymac" patches from #3492
- add GUI option "Default help visibility: Help sections within the webConfigurator will be hidden by default" `[webguihelphidden]`
- `pfSenseHelpers.js` - comment out L416-420 (related to above change)
- `interfaces_assign.php` now also sorts interfaces by description, and also sorts `portlist` dropdown menus
- `firewall_aliases.php` (fix tiny typo `pfenseHelpers.js` => `pfSenseHelpers.js`)
- ~35 php pages edited to adjust for new infoblock behavior

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by luckman212** [comment]
Not sure why I got tagged missing-CLA, I have submitted patches before and signed the CLA a long time ago. Is this because of my username change?

**Comment by luckman212** [comment]
Forgot to state the reason for the "infoblock" display changes: it's to fix the momentary flicker of the box as it is first rendered and then quickly disappears when the page loads and the javascript hides the div. This new way looks cleaner and doesn't cause the UI to jump.

**Comment by sbeaver-netgate** [comment]
This request contains four (?) unrelated changes. Please resubmit as four separate PRs 

I believe it should be possible to to use the webguihelphidden setting to control the value of a PHP var in (for example) head.inc, and to then read that variable in pfSenseHelpers.js to control the infoblock action. This would: A) No longer require the programmer to remember to add the extra logic when an infoblock is required, B) Maintain the "automatic" nature of the infobloc class, and C) no longer require the editing of +/40 pages

**Comment by phil-davis** [comment]
Or some common function to print the start div of an infoblock, like example code in https://github.com/phil-davis/pfsense/commit/6fa8dd28dfe6652fbdd4495142948039edc83709

**Comment by sbeaver-netgate** [comment]
That is a little cleaner, but still required edits to +/- 40 files. I would prefer that the control is respected in JS.

**Comment by phil-davis** [comment]
Yes, true. I had been making my refactoring example at the time of @sbeaver-netgate first comment. Now I have read the comment properly, I agree. The
```
style="display: none;"
```
bit can be inserted using a PHP var that is either blank or set to that string based on webguihelphidden...

**Comment by luckman212** [comment]
I see I got my CLA status back, so I will refactor these and submit new individual PRs shortly. Thanks

**Comment by ExolonDX** [comment]
I thought one of the ideas behind using Bootstrap is to get rid of inline CSS styles:

Showing and hiding content:-
http://getbootstrap.com/css/#helper-classes-show-hide

examples:-
http://stackoverflow.com/questions/18568736/how-to-hide-element-using-twitter-bootstrap-3-and-show-it-using-jquery
http://stackoverflow.com/questions/10349285/twitter-bootstrap-hide-css-class-and-jquery

**Comment by sbeaver-netgate** [comment]
Please refactor as requested

**Comment by sbeaver-netgate** [comment]
Requested changes not implemented in 9 months. please resubmit if still desired.

**Pull request closed without merging**
