### PR TITLE
Add option to not register IPv4 and/or IPv6 addresses.

### PR DESCRIPTION
**Pull request by Robert-Nelson**
This change adds options to prevent registering IPv4 or IPv6 addresses.

### CODE REVIEW

**Comment by rbgarga** [comment]
IMO it would be better if you add a single field to let user choose which field(s) he wants to update, A, AAAA or both, both being the default option.

**Comment by Robert-Nelson** [comment]
Fixed to use radio buttons to select between IPv4, IPv6 or Both.

**Comment by rbgarga** [comment]
Field name would make more sense to be called "protocol" or "ip_protocol" instead of addresses

**Comment by Robert-Nelson** [comment]
I disagree, the purpose of dynamic DNS is to register addresses not protocols.  This option controls which type of addresses, addresses used by the IP4 or IP6 protocols.  If you don't like addresses then perhaps addresstypes but I believe calling it protocols would be misleading and incorrect.

**Comment by rbgarga** [comment]
Yeah, you are right, they are address types and not protocols

**Comment by Robert-Nelson** [comment]
Darn you were too quick, I just added a change to rename it to addresstypes which I think is better based on your feedback.

**Comment by rbgarga** [comment]
yeah, it sounds great. I'll test and merge

**Comment by rbgarga** [comment]
I'm just wondering about another option, call it 'Record type' and options 'A', 'AAAA'. Maybe it would make more sense for a DNS page

**Comment by Robert-Nelson** [comment]
I thought of that too, but I think it is too much of a technical implementation detail and might not be as obvious to most administrators.

**Comment by rbgarga** [comment]
I also discussed it with @jim-p and he suggested to change it to 'Record type' and use in the description A (IPv4) and AAAA (IPv6). Could you do the changes?

**Comment by Robert-Nelson** [comment]
Okay I've made the changes.

**Pull request merged**
