### PR TITLE
GratisDNS support for hosts without subdomains

### PR DESCRIPTION
**Pull request by doktornotor**
Resubmit of #1793

### CODE REVIEW

**Comment by rbgarga** [comment]
@doktornotor I was thinking about those PRs you are re-submitting to fix conflicts, and I believe we have a problem. Original author is getting lost, and this is not good.
I would like to ask you to use --author parameter on git commit, adding original author, this would preserve history and people that originally wrote the changes.

**Comment by doktornotor** [comment]
Yeah, the original author is getting lost. Because, normally, the original author is either gone or annoyed like hell by wasting time.

Closed all the offending comments. You are welcome to either merge those manually or ignore those forever. I seriously do NOT have time for similar bullshit.

Have a nice day.

**Comment by gonzopancho** [comment]
Jacob, throttle back some.

**Comment by doktornotor** [comment]
@gonzopancho I am pretty much throttled. Original commiters have been notified and politely asked to recycle my wasted time and resubmit their contributions from my PRs, until you break it again. I have even apologized on your behalf for wasting their time. Afraid, they just won't do the legwork regardless. Why should they after all? Not their fault.

That, or you can do that manually with whatever git magic commands you wish.

**Comment by shamanime** [comment]
Please guide me if this is not the place to post about this... I got here because of #1916.

I am having trouble using CloudFlare and a domain like "test.example.com.br".
The log says "ERROR - Zone or Host ID was not found, check your hostname.".

Seems like it's not parsing the TLD correctly.

Changing to another domain with just ".com" works.

**Pull request closed without merging**
