### PR TITLE
Escape username before use in CP SQL

### PR DESCRIPTION
**Pull request by phil-davis**
A maybe "better" version to try.

### CODE REVIEW

**Comment by phil-davis** [comment]
@heper Can you check if this version works?
The call to escapeString should be a more generic thing that will work for all weird strings for the rest of eternity.

**Comment by heper** [comment]
@phil-davis seems to work fine. thanks :)

**Comment by phil-davis** [comment]
Thanks for the quick testing! Then this is the preferred fix IMHO.

**Comment by phil-davis** [comment]
Redmine issue https://redmine.pfsense.org/issues/6203 created to document this.

**Pull request merged**
