### PR TITLE
Do not echo printf return value

### PR DESCRIPTION
**Pull request by NewEraCracker**
The current implementation would echo both the contents and printf return value which is incorrect. This commit fixes the issue.

### CODE REVIEW

**Comment by sbeaver-netgate** [comment]
Perhaps <?=sprintf(... )?> would accomplish the same thing, but be more in line with the style of project?

**Comment by NewEraCracker** [comment]
Yes. I can change to that if you wish.

**Comment by sbeaver-netgate** [comment]
Thanks :)

**Comment by NewEraCracker** [comment]
Done.

**Pull request merged**
