### PR TITLE
Improve DynDNS help text readability

### PR DESCRIPTION
**Pull request by Bojan023**
[ x] Ready for review

- To improve readability I've reordered hostname, username, password, zone id help texts alphabetically. 
- Changed 'type' to 'provider' for consistency  (username help text).
- Capitalized one instance of "dns" to "DNS" (ttl help text).

### CODE REVIEW

**Review by jim-p — APPROVED** [review]

**Comment by jim-p** [comment]
To effectively track changes and bug/feature requests, we require an entry on the [pfSense Redmine issue tracker](https://redmine.pfsense.org) associated with every pull request, and likewise the Redmine entry should also have a link back to the pull request.

Please associate this PR to a Redmine issue either by locating an existing issue at https://redmine.pfsense.org or by creating a new issue. Add a link to the Redmine issue that points to this PR, and also add a link on the PR to the Redmine issue.

For more information, see https://docs.netgate.com/pfsense/en/latest/development/pull-request.html
Thanks!

**Comment by Bojan023** [comment]
Redmine link: https://redmine.pfsense.org/issues/14186?next_issue_id=14185

**Comment by jim-p** [comment]
Thanks!

**Comment by marcos-ng** [comment]
Already merged.

**Pull request closed without merging**
