### PR TITLE
dhcp-relay, combine clean and fix code for destination interface discovery

### PR DESCRIPTION
**Pull request by PiBa-NL**
dhcp-relay, combine clean and fix code for destination interface discovery

p.s.
code works better than before imho, but does need checking if the 4 step route discovery is actually the right way to proceed.. thanks in advance.

### CODE REVIEW

**Comment by PiBa-NL** [comment]
@jim-p, thanks that function seems to do (almost) the same, but then better :).. Removed my get_realinterface_for_destination replacement for the old implementation by this guess_interface_from_ip one. Commit added.

**Comment by PiBa-NL** [comment]
@sbeaver-netgate , can you specify what changes are requested by you?

**Comment by rbgarga** [comment]
@sbeaver-netgate did you request any change on this PR?

**Comment by PiBa-NL** [comment]
@sbeaver-netgate please tell, what changes do you want? if none can you remove the 'changes requested' label .?

**Comment by sbeaver-netgate** [comment]
The label was added for hte Jim-P Jun 5 change request. Now resolved.

**Comment by PiBa-NL** [comment]
Yes funny though,
5 jun. 2017 15:54 CEST - Changes requested by Jim-P
5 jun. 2017 18:07 CEST - New commit pushed that included the requested changes
20 jun. 2017 16:30 CEST - ChangesRequested label added by SBeaver
That seemed a little late if it was related to Jim-P's request.. So was wondering if you spotted something that needed changing yourself. I understand that was not the case now :)

Thanks for pulling 👍

**Comment by sbeaver-netgate** [comment]
I look through the PRs from time to time and add any labels I think are helpful - it least it shows they are not forgotten. Sometimes I am late to the party :(

Steve
--
Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com | www.netgate.com

**Pull request merged**
