### PR TITLE
Button to clear the ARP cache. Issue #4038

### PR DESCRIPTION
**Pull request by vktg**
- [ ] Redmine Issue: https://redmine.pfsense.org/issues/4038
- [ ] Ready for review

### CODE REVIEW

**Comment by vktg** [comment]
works fine, but for some reason it always shows "CSRF check failed" after pressing the button

**Comment by vktg** [comment]
ok, I removed this code,
seems to be working fine

**Comment by vktg** [comment]
Updated
now works correctly with CSRF

**Review by jim-p — APPROVED** [review]
Appears to work fine, no CSRF errors and the table clears as expected

**Pull request merged**
