### PR TITLE
fbegin.inc and fend.inc are no longer used

### PR DESCRIPTION
**Pull request by phil-davis**
As far as I can tell these are no longer in use.
And I suspect there is a file somewhere where these should be listed so that they will be cleaned up on upgrades etc - but I can;t remember where it is.

### CODE REVIEW

**Comment by rbgarga** [comment]
yes, it's src/etc/pfSense.obsoletedfiles

**Comment by rbgarga** [comment]
@phil-davis did you check all packages on pfSense/FreeBSD-ports to make sure nobody is using it?

**Comment by doktornotor** [comment]
These are still lingering in 
- Suricata
- Snort
- tinc

Will do some PRs shortly.

**Comment by doktornotor** [comment]
Should be all, at least to GitHub search.

**Comment by phil-davis** [comment]
Added to obsolete files list. This should be good to go once the FreeBSD-ports changes have been merged/released.

**Pull request merged**
