### PR TITLE
Convert bit-based error types to human readable E_* codes when reporting errors

### PR DESCRIPTION
**Pull request by stilez**
error_get_last() includes a bit-based error type which corresponds to E_WARNING, E_DEPRECATED etc. Report the text tags rather than the numeric code if possible, as it makes more sense on reading notices.

### CODE REVIEW

**Comment by PiBa-NL** [comment]
Any reason not to write the array values as they are?:
```
	$PHP_error_types = array (
		   1 => 'E_ERROR',           2 => 'E_WARNING',           4 => 'E_PARSE',            8 => 'E_NOTICE',
		  16 => 'E_CORE_ERROR',     32 => 'E_CORE_WARNING',     64 => 'E_COMPILE_ERROR',  256 => 'E_USER_ERROR',
		 512 => 'E_USER_WARNING', 1024 => 'E_USER_NOTICE',    2048 => 'E_STRICT',        4096 => 'E_RECOVERABLE_ERROR',
		8192 => 'E_DEPRECATED',  16384 => 'E_USER_DEPRECATED'
	);
```
Looks like it would be faster even if only by a millisecond. As globals is included almost anywhere there is no point to doing the string parsing and eval dynamic code every time from php code.
imho anyhow, @jim-p what do you think.?.

**Comment by jim-p** [comment]
If you're generating it from a static list anyhow, may as well do the array method rather than a foreach/eval loop.

If you don't want to hardcode anything and don't care about speed, you could parse it out of get_defined_constants(true) by getting any E_* variables from the 'core' section of the returned list.

**Comment by stilez** [comment]
Makes sense. I did it that way because of the old principle that codes intended for human use tend to be static, those for internal use (their numeric equivalents) are more prone to change. Probably not relevant here. Worth changing to fully static definition?

**Comment by sbeaver-netgate** [comment]
Please consider using the array as PiBa-NL suggests, and resolve conflicts

**Comment by jim-p** [comment]
In an effort to improve the tracking of changes and bug/feature requests, we have decided to require an entry on the [pfSense Redmine issue tracker](https://redmine.pfsense.org) associated with every pull request, and likewise the Redmine entry should also have a link back to the pull request.

If you could, please associate this PR to a Redmine issue either by locating an existing issue at https://redmine.pfsense.org or by creating a new issue. Add a link to the Redmine issue that points to this PR, and also add a link on the PR to the Redmine issue.

For more information, see https://doc.pfsense.org/index.php/Submitting_a_Pull_Request_via_Github

Thanks!

**Comment by sbeaver-netgate** [comment]
Please rebase to resolve conflict. We can then merge this PR.

**Comment by sbeaver-netgate** [comment]
Closing due to unresolved conflicts. Please resubmit if you are able to rebase.

**Pull request closed without merging**
