### PR TITLE
Improve IPsec crypto algorithm support

### PR DESCRIPTION
**Pull request by baxeno**
Extended NIST + Brainpool Elliptic Curve support.
Extended AES Galois/Counter Mode support.
NIST ecp521 typo bugfix.
Keyid typo bugfix.

Strongswan cipher suite names can be found here:
https://wiki.strongswan.org/projects/strongswan/wiki/IKEv2CipherSuites

### CODE REVIEW

**Comment by baxeno** [comment]
I forget to add a commit with bp to vpn_ipsec_convert_to_modp(), will push commit later today.

**Comment by baxeno** [comment]
All commits has been added and tested.

**Comment by ermal** [comment]
Can you sign the CLA please

**Comment by baxeno** [comment]
CLA signed.

**Pull request merged**
