### PR TITLE
Provide EKU info in cert manager

### PR DESCRIPTION
**Pull request by bruno-infotrad**
As per discussion in https://github.com/pfsense/pfsense/pull/3234, add a column for EKU info in cert manager

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by bruno-infotrad** [comment]
Signed the CLA.

**Comment by rbgarga** [comment]
Assigning to @jim-p since he was involved in #3234 discussion

**Comment by jim-p** [comment]
It's a good start, can you change the column to "Purposes" and move the CA:Yes/No and Server:Yes/No from the first column into there as well? Seems to make more sense to keep them all together.

**Comment by jim-p** [comment]
I'm implementing this in a different way. The extra column was not helping the formatting and it needed a couple tweaks. It will be pushed shortly.

**Pull request closed without merging**
