### PR TITLE
Add Form_IpAddress cases for Alias

### PR DESCRIPTION
**Pull request by phil-davis**
Callers of Form_IpAddress sometimes need to allow the user to enter an IP address (V4, V6 or either) or an Alias.
Add cases here that have the appropriate input regex patterns and message for the hover-text.

### CODE REVIEW

**Comment by rbgarga** [comment]
I would like to hear from @sbeaver-netgate about this one. Thoughts?

**Comment by sbeaver-netgate** [comment]
I have several thought on the subject. Will post as soon as I have time, but later this week

**Comment by rbgarga** [comment]
I'll assign it and other that depends of it to you then. Thanks!

**Comment by phil-davis** [comment]
#3245 is a more OO way to do this.
@sbeaver-netgate perhaps you were thinking more like that? Or?

**Comment by phil-davis** [comment]
Closing in favour of #3248

**Pull request closed without merging**
