### PR TITLE
Bug #5527 wizard breadcrumb Concept

### PR DESCRIPTION
**Pull request by heper**
This would require some minor adjustments to the wizards xml , for it to make sense everywhere.

### CODE REVIEW

**Comment by sbeaver-netgate** [comment]
Perhaps a good compromise would be to note here what those "minor adjustments" should be. THat would allow others to more easily take on the work?

**Comment by heper** [comment]
@sbeaver-netgate found some time: i've adjusted the xml's but they might require some polishing.
the <description> tags could use some more information, but i'm not all that good with words (&  english isn't my native language)

**Comment by sbeaver-netgate** [comment]
Thank you!

**Comment by sbeaver-netgate** [comment]
Thanks again. Though it may not be your first language, your English is better than some people for whom it is their only language :)

**Pull request merged**
